import { Phase, Subject } from './types';

// ===== HIGH SCHOOL YEAR 3 GENERAL / السنة الثالثة الثانوية (عام) =====

export const excel_1447_high_grade_3_general_sem_1: Subject[] = [
  {
    id: 'high_3_gen_1_1',
    name: 'الرياضيات 3-1',
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: 'عام',
  },
  {
    id: 'high_3_gen_1_2',
    name: 'الكفايات اللغوية 3-1',
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: 'عام',
  },
  {
    id: 'high_3_gen_1_3',
    name: 'الفيزياء 3-1',
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: 'عام',
  },
  {
    id: 'high_3_gen_1_4',
    name: 'الكيمياء 3-1',
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: 'عام',
  },
  {
    id: 'high_3_gen_1_5',
    name: 'الأحياء 3-1',
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: 'عام',
  },
  {
    id: 'high_3_gen_1_6',
    name: 'التفسير 1',
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: 'عام',
  },
  {
    id: 'high_3_gen_1_7',
    name: 'اللغة الإنجليزية 3-1',
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: 'عام',
  },
];

export const excel_1447_high_grade_3_general_sem_2: Subject[] = [
  {
    id: 'high_3_gen_2_1',
    name: 'الرياضيات 3-2',
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: 'عام',
  },
  {
    id: 'high_3_gen_2_2',
    name: 'الكفايات اللغوية 3-2',
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: 'عام',
  },
  {
    id: 'high_3_gen_2_3',
    name: 'الدراسات الأدبية',
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: 'عام',
  },
  {
    id: 'high_3_gen_2_4',
    name: 'الفيزياء 3-2',
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: 'عام',
  },
  {
    id: 'high_3_gen_2_5',
    name: 'الكيمياء 3-2',
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: 'عام',
  },
  {
    id: 'high_3_gen_2_6',
    name: 'اللغة الإنجليزية 3-2',
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: 'عام',
  },
];

// ===== HIGH SCHOOL YEAR 3 COMPUTER & ENGINEERING / السنة الثالثة (حاسب وهندسة) =====

export const excel_1447_high_grade_3_cs_eng_sem_1: Subject[] = [
  {
    id: 'high_3_cs_1_1',
    name: 'الرياضيات 3-1',
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: 'حاسب وهندسة',
  },
  {
    id: 'high_3_cs_1_2',
    name: 'الكفايات اللغوية 3-1',
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: 'حاسب وهندسة',
  },
  {
    id: 'high_3_cs_1_3',
    name: 'الفيزياء 3-1',
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: 'حاسب وهندسة',
  },
  {
    id: 'high_3_cs_1_4',
    name: 'الهندسة الكهربائية 1',
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: 'حاسب وهندسة',
  },
  {
    id: 'high_3_cs_1_5',
    name: 'تقنية الحاسب 1',
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: 'حاسب وهندسة',
  },
  {
    id: 'high_3_cs_1_6',
    name: 'التفسير 1',
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: 'حاسب وهندسة',
  },
  {
    id: 'high_3_cs_1_7',
    name: 'اللغة الإنجليزية 3-1',
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: 'حاسب وهندسة',
  },
];

export const excel_1447_high_grade_3_cs_eng_sem_2: Subject[] = [
  {
    id: 'high_3_cs_2_1',
    name: 'الرياضيات 3-2',
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: 'حاسب وهندسة',
  },
  {
    id: 'high_3_cs_2_2',
    name: 'الكفايات اللغوية 3-2',
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: 'حاسب وهندسة',
  },
  {
    id: 'high_3_cs_2_3',
    name: 'الفيزياء 3-2',
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: 'حاسب وهندسة',
  },
  {
    id: 'high_3_cs_2_4',
    name: 'الهندسة المدنية 1',
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: 'حاسب وهندسة',
  },
  {
    id: 'high_3_cs_2_5',
    name: 'أمن الشبكات 1',
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: 'حاسب وهندسة',
  },
  {
    id: 'high_3_cs_2_6',
    name: 'اللغة الإنجليزية 3-2',
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: 'حاسب وهندسة',
  },
];

// ===== HIGH SCHOOL YEAR 3 HEALTH & LIFE / السنة الثالثة (صحة وحياة) =====

export const excel_1447_high_grade_3_health_sem_1: Subject[] = [
  {
    id: 'high_3_health_1_1',
    name: 'الرياضيات 3-1',
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: 'صحة وحياة',
  },
  {
    id: 'high_3_health_1_2',
    name: 'الكفايات اللغوية 3-1',
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: 'صحة وحياة',
  },
  {
    id: 'high_3_health_1_3',
    name: 'الأحياء 3-1',
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: 'صحة وحياة',
  },
  {
    id: 'high_3_health_1_4',
    name: 'الكيمياء 3-1',
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: 'صحة وحياة',
  },
  {
    id: 'high_3_health_1_5',
    name: 'الصحة والحياة 1',
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: 'صحة وحياة',
  },
  {
    id: 'high_3_health_1_6',
    name: 'التفسير 1',
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: 'صحة وحياة',
  },
  {
    id: 'high_3_health_1_7',
    name: 'اللغة الإنجليزية 3-1',
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: 'صحة وحياة',
  },
];

export const excel_1447_high_grade_3_health_sem_2: Subject[] = [
  {
    id: 'high_3_health_2_1',
    name: 'الرياضيات 3-2',
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: 'صحة وحياة',
  },
  {
    id: 'high_3_health_2_2',
    name: 'الكفايات اللغوية 3-2',
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: 'صحة وحياة',
  },
  {
    id: 'high_3_health_2_3',
    name: 'الأحياء 3-2',
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: 'صحة وحياة',
  },
  {
    id: 'high_3_health_2_4',
    name: 'علم الأمراض 1',
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: 'صحة وحياة',
  },
  {
    id: 'high_3_health_2_5',
    name: 'الإسعافات الأولية 1',
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: 'صحة وحياة',
  },
  {
    id: 'high_3_health_2_6',
    name: 'اللغة الإنجليزية 3-2',
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: 'صحة وحياة',
  },
];
