import { Phase, Subject } from './types';

// الابتدائية (عام) | الصف الأول
export const excel_elementary_general_grade1: Subject[] = [
  {
    id: "s_0001",
    name: "اللغة العربية",
    specializationIds: [],
    periodsPerClass: 8,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "s_0002",
    name: "الرياضيات",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
];

// الابتدائية (عام) | الصف الثاني
export const excel_elementary_general_grade2: Subject[] = [
  {
    id: "s_0003",
    name: "القرآن الكريم والدراسات الإسلامية",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "s_0004",
    name: "اللغة العربية",
    specializationIds: [],
    periodsPerClass: 7,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
];

// الابتدائية (عام) | الصف الثالث
export const excel_elementary_general_grade3: Subject[] = [
  {
    id: "s_0005",
    name: "اللغة العربية",
    specializationIds: [],
    periodsPerClass: 6,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "s_0006",
    name: "العلوم",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
];

// الابتدائية (عام) | الصف الأول / الثاني / الثالث
export const excel_elementary_general_mixed: Subject[] = [
  {
    id: "s_0007",
    name: "القرآن الكريم والدراسات الإسلامية",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "s_0008",
    name: "العلوم",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "s_0009",
    name: "اللغة الإنجليزية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "s_0010",
    name: "التربية الفنية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "s_0011",
    name: "التربية البدنية والدفاع عن النفس",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "s_0012",
    name: "المهارات الحياتية والأسرية",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "s_0013",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "s_0014",
    name: "الرياضيات",
    specializationIds: [],
    periodsPerClass: 6,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
];

// الابتدائية (عام) | الصفوف العليا (4-6)
export const excel_elementary_general_upper: Subject[] = [
  {
    id: "s_0015",
    name: "القرآن الكريم والدراسات الإسلامية",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "s_0016",
    name: "اللغة العربية",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "s_0017",
    name: "الدراسات الاجتماعية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "s_0018",
    name: "الرياضيات",
    specializationIds: [],
    periodsPerClass: 6,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "s_0019",
    name: "العلوم",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "s_0020",
    name: "اللغة الإنجليزية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "s_0021",
    name: "المهارات الرقمية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "s_0022",
    name: "التربية الفنية",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "s_0023",
    name: "التربية البدنية والدفاع عن النفس",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "s_0024",
    name: "المهارات الحياتية والأسرية",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "s_0025",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
];

// الابتدائية (تحفيظ) | الصف الأول
export const excel_elementary_quran_grade1: Subject[] = [
  {
    id: "s_0026",
    name: "اللغة العربية",
    specializationIds: [],
    periodsPerClass: 8,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "s_0027",
    name: "الرياضيات",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
];

// الابتدائية (تحفيظ) | الصف الثاني
export const excel_elementary_quran_grade2: Subject[] = [
  {
    id: "s_0028",
    name: "اللغة العربية",
    specializationIds: [],
    periodsPerClass: 7,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
];

// الابتدائية (تحفيظ) | الصف الثالث
export const excel_elementary_quran_grade3: Subject[] = [
  {
    id: "s_0029",
    name: "اللغة العربية",
    specializationIds: [],
    periodsPerClass: 6,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "s_0030",
    name: "العلوم",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
];

// الابتدائية (تحفيظ) | الصف الأول / الثاني / الثالث
export const excel_elementary_quran_mixed: Subject[] = [
  {
    id: "s_0031",
    name: "القرآن الكريم والدراسات الإسلامية",
    specializationIds: [],
    periodsPerClass: 9,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "s_0032",
    name: "العلوم",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "s_0033",
    name: "اللغة الإنجليزية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "s_0034",
    name: "التربية الفنية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "s_0035",
    name: "التربية البدنية والدفاع عن النفس",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "s_0036",
    name: "المهارات الحياتية والأسرية",
    specializationIds: [],
    periodsPerClass: 6,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "s_0037",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "s_0038",
    name: "الرياضيات",
    specializationIds: [],
    periodsPerClass: 6,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
];

// الابتدائية (تحفيظ) | الصفوف العليا (4-6)
export const excel_elementary_quran_upper: Subject[] = [
  {
    id: "s_0039",
    name: "القرآن الكريم والدراسات الإسلامية",
    specializationIds: [],
    periodsPerClass: 8,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "s_0040",
    name: "التجويد",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "s_0041",
    name: "اللغة العربية",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "s_0042",
    name: "الدراسات الاجتماعية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "s_0043",
    name: "الرياضيات",
    specializationIds: [],
    periodsPerClass: 6,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "s_0044",
    name: "العلوم",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "s_0045",
    name: "اللغة الإنجليزية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "s_0046",
    name: "المهارات الرقمية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "s_0047",
    name: "التربية الفنية",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "s_0048",
    name: "التربية البدنية والدفاع عن النفس",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "s_0049",
    name: "المهارات الحياتية والأسرية",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
];

// السنة الأولى الثانوية المشتركة | الأول
export const excel_high_y1_general_mixed: Subject[] = [
  {
    id: "s_0050",
    name: "القرآن الكريم وتفسيره",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0051",
    name: "الرياضيات 1",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0052",
    name: "اللغة الإنجليزية 1",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0053",
    name: "التقنية الرقمية 1",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0054",
    name: "الكفايات اللغوية 1",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0055",
    name: "مادة العلوم (كيمياء/فيزياء)",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0056",
    name: "التفكير الناقد",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0057",
    name: "التربية الصحية والبدنية 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0058",
    name: "الرياضيات 1",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0059",
    name: "اللغة الإنجليزية 1",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0060",
    name: "التقنية الرقمية 1",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0061",
    name: "الأحياء 1",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0062",
    name: "مادة العلوم (كيمياء/فيزياء)",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0063",
    name: "الكفايات اللغوية 1",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0064",
    name: "علم البيئة",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0065",
    name: "الحديث 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0066",
    name: "المعرفة المالية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0067",
    name: "الدراسات الاجتماعية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0068",
    name: "التربية المهنية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0069",
    name: "التربية الصحية والبدنية 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
];

// السنة الثانية الثانوية مسار حاسب وهندسة | الأول
export const excel_high_y2_cs_eng_mixed: Subject[] = [
  {
    id: "s_0070",
    name: "الرياضيات 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0071",
    name: "اللغة الإنجليزية 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0072",
    name: "الفيزياء 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0073",
    name: "إنترنت الأشياء 1-1",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0074",
    name: "الكفايات اللغوية 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0075",
    name: "التاريخ",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0076",
    name: "اللياقة والثقافة الصحية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0077",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0078",
    name: "الرياضيات 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0079",
    name: "اللغة الإنجليزية 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0080",
    name: "الكيمياء 2",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0081",
    name: "علم البيانات",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0082",
    name: "الهندسة",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0083",
    name: "التوحيد 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0084",
    name: "الجغرافيا",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0085",
    name: "اللياقة والثقافة الصحية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0086",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
];

// السنة الثانية الثانوية مسار عام | الأول
export const excel_high_y2_general_mixed: Subject[] = [
  {
    id: "s_0087",
    name: "الرياضيات 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0088",
    name: "اللغة الإنجليزية 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0089",
    name: "الفيزياء 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0090",
    name: "الكيمياء 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0091",
    name: "الأحياء 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0092",
    name: "الكفايات اللغوية 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0093",
    name: "التاريخ",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0094",
    name: "اللياقة والثقافة الصحية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0095",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0096",
    name: "الرياضيات 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0097",
    name: "اللغة الإنجليزية 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0098",
    name: "الكيمياء 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0099",
    name: "الأحياء 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0100",
    name: "التقنية الرقمية 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0101",
    name: "التوحيد 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0102",
    name: "الجغرافيا",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0103",
    name: "الفنون",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0104",
    name: "اللياقة والثقافة الصحية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0105",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0106",
    name: "الرياضيات 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0107",
    name: "اللغة الإنجليزية 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0108",
    name: "الكيمياء 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0109",
    name: "الأحياء 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0110",
    name: "مبادئ العلوم الصحية",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0111",
    name: "الكفايات اللغوية 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0112",
    name: "اللياقة والثقافة الصحية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0113",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0114",
    name: "الرياضيات 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0115",
    name: "اللغة الإنجليزية 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0116",
    name: "الفيزياء 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0117",
    name: "الرعاية الصحية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0118",
    name: "التقنية الرقمية 2",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0119",
    name: "التوحيد 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0120",
    name: "اللياقة والثقافة الصحية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0121",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0122",
    name: "اللغة الإنجليزية 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0123",
    name: "صناعة القرار في الأعمال",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0124",
    name: "مقدمة في الأعمال",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0125",
    name: "الكفايات اللغوية 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0126",
    name: "الإدارة المالية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0127",
    name: "التوحيد 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0128",
    name: "التاريخ",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0129",
    name: "اللياقة والثقافة الصحية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0130",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0131",
    name: "اللغة الإنجليزية 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0132",
    name: "صناعة القرار في الأعمال",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0133",
    name: "مقدمة في الأعمال",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0134",
    name: "مبادئ الاقتصاد",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0135",
    name: "مبادئ الإدارة",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0136",
    name: "التفسير 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0137",
    name: "الجغرافيا",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0138",
    name: "الفنون",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0139",
    name: "اللياقة والثقافة الصحية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0140",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
];

// السنة الثانية الثانوية مسار شرعي | الأول
export const excel_high_y2_islamic_mixed: Subject[] = [
  {
    id: "s_0141",
    name: "القرآن الكريم 1",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0142",
    name: "اللغة الإنجليزية 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0143",
    name: "الكفايات اللغوية 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0144",
    name: "القراءات 1",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0145",
    name: "الحديث 2",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0146",
    name: "التوحيد 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0147",
    name: "التاريخ",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0148",
    name: "اللياقة والثقافة الصحية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0149",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0150",
    name: "القرآن الكريم 1",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0151",
    name: "اللغة الإنجليزية 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0152",
    name: "علوم القرآن",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0153",
    name: "القراءات 2",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0154",
    name: "مصطلح الحديث",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0155",
    name: "التوحيد 2",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0156",
    name: "الجغرافيا",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0157",
    name: "الفنون",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0158",
    name: "اللياقة والثقافة الصحية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0159",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
];

// السنة الثالثة الثانوية مسار إدارة أعمال | الأول
export const excel_high_y3_business_mixed: Subject[] = [
  {
    id: "s_0160",
    name: "اللغة الإنجليزية 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "إدارة أعمال",
  },
  {
    id: "s_0161",
    name: "إدارة الفعاليات",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "إدارة أعمال",
  },
  {
    id: "s_0162",
    name: "تخطيط الحملات التسويقية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "إدارة أعمال",
  },
  {
    id: "s_0163",
    name: "مبادئ القانون",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "إدارة أعمال",
  },
  {
    id: "s_0164",
    name: "الدراسات البلاغية والنقدية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "إدارة أعمال",
  },
  {
    id: "s_0165",
    name: "الإحصاء",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "إدارة أعمال",
  },
  {
    id: "s_0166",
    name: "التربية الصحية والبدنية 2",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "إدارة أعمال",
  },
  {
    id: "s_0167",
    name: "البحث ومصادر المعلومات",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "إدارة أعمال",
  },
  {
    id: "s_0168",
    name: "مشروع التخرج",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "إدارة أعمال",
  },
  {
    id: "s_0169",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.HIGH],
    department: "إدارة أعمال",
  },
  {
    id: "s_0170",
    name: "اللغة الإنجليزية 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "إدارة أعمال",
  },
  {
    id: "s_0171",
    name: "إدارة الفعاليات",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "إدارة أعمال",
  },
  {
    id: "s_0172",
    name: "تخطيط الحملات التسويقية",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "إدارة أعمال",
  },
  {
    id: "s_0173",
    name: "السكرتارية والإدارة المكتبية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "إدارة أعمال",
  },
  {
    id: "s_0174",
    name: "تطبيقات في القانون",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "إدارة أعمال",
  },
  {
    id: "s_0175",
    name: "الفقه 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "إدارة أعمال",
  },
  {
    id: "s_0176",
    name: "الدراسات الأدبية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "إدارة أعمال",
  },
  {
    id: "s_0177",
    name: "الدراسات النفسية والاجتماعية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "إدارة أعمال",
  },
  {
    id: "s_0178",
    name: "التقنية الرقمية 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "إدارة أعمال",
  },
  {
    id: "s_0179",
    name: "المواطنة الرقمية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "إدارة أعمال",
  },
  {
    id: "s_0180",
    name: "المهارات الحياتية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "إدارة أعمال",
  },
  {
    id: "s_0181",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "إدارة أعمال",
  },
];

// السنة الثالثة الثانوية مسار حاسب وهندسة | الأول
export const excel_high_y3_cs_eng_mixed: Subject[] = [
  {
    id: "s_0182",
    name: "الرياضيات 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0183",
    name: "اللغة الإنجليزية 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0184",
    name: "الفيزياء 3",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0185",
    name: "الكيمياء 3",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0186",
    name: "علوم الأرض والفضاء",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0187",
    name: "الذكاء الاصطناعي",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0188",
    name: "هندسة البرمجيات",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0189",
    name: "التربية الصحية والبدنية 2",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0190",
    name: "مشروع التخرج",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0191",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0192",
    name: "الرياضيات 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0193",
    name: "اللغة الإنجليزية 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0194",
    name: "الأمن السيبراني",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0195",
    name: "التصميم الهندسي",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0196",
    name: "الفقه 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0197",
    name: "المهارات الحياتية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0198",
    name: "البحث ومصادر المعلومات",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
  {
    id: "s_0199",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "حاسب وهندسة",
  },
];

// السنة الثالثة الثانوية مسار عام | الأول
export const excel_high_y3_general_mixed: Subject[] = [
  {
    id: "s_0200",
    name: "الرياضيات 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0201",
    name: "اللغة الإنجليزية 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0202",
    name: "الفيزياء 3",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0203",
    name: "الكيمياء 3",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0204",
    name: "الأحياء 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0205",
    name: "علوم الأرض والفضاء",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0206",
    name: "المجال الاختياري",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0207",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0208",
    name: "الرياضيات 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0209",
    name: "اللغة الإنجليزية 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0210",
    name: "الفيزياء 3",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0211",
    name: "الكيمياء 3",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0212",
    name: "الأحياء 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0213",
    name: "علوم الأرض والفضاء",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0214",
    name: "الفقه 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0215",
    name: "الدراسات الأدبية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0216",
    name: "الدراسات النفسية والاجتماعية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0217",
    name: "التقنية الرقمية 3",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0218",
    name: "المواطنة الرقمية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0219",
    name: "المجال الاختياري",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "s_0220",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
];

// السنة الثالثة الثانوية مسار صحة وحياة | الأول
export const excel_high_y3_health_mixed: Subject[] = [
  {
    id: "s_0221",
    name: "الرياضيات 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "صحة وحياة",
  },
  {
    id: "s_0222",
    name: "اللغة الإنجليزية 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "صحة وحياة",
  },
  {
    id: "s_0223",
    name: "الأحياء 3",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "صحة وحياة",
  },
  {
    id: "s_0224",
    name: "أنظمة جسم الإنسان",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "صحة وحياة",
  },
  {
    id: "s_0225",
    name: "علوم الأرض والفضاء",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "صحة وحياة",
  },
  {
    id: "s_0226",
    name: "المهارات الحياتية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "صحة وحياة",
  },
  {
    id: "s_0227",
    name: "التربية الصحية والبدنية 2",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "صحة وحياة",
  },
  {
    id: "s_0228",
    name: "مشروع التخرج",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "صحة وحياة",
  },
  {
    id: "s_0229",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "صحة وحياة",
  },
  {
    id: "s_0230",
    name: "الرياضيات 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "صحة وحياة",
  },
  {
    id: "s_0231",
    name: "اللغة الإنجليزية 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "صحة وحياة",
  },
  {
    id: "s_0232",
    name: "الفيزياء 3",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "صحة وحياة",
  },
  {
    id: "s_0233",
    name: "الكيمياء 3",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "صحة وحياة",
  },
  {
    id: "s_0234",
    name: "الفقه 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "صحة وحياة",
  },
  {
    id: "s_0235",
    name: "الإحصاء",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "صحة وحياة",
  },
  {
    id: "s_0236",
    name: "البحث ومصادر المعلومات",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "صحة وحياة",
  },
  {
    id: "s_0237",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.HIGH],
    department: "صحة وحياة",
  },
];

// السنة الثالثة الثانوية مسار شرعي | الأول
export const excel_high_y3_islamic_mixed: Subject[] = [
  {
    id: "s_0238",
    name: "القرآن الكريم 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0239",
    name: "اللغة الإنجليزية 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0240",
    name: "الفقه 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0241",
    name: "مبادئ القانون",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0242",
    name: "الدراسات البلاغية والنقدية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0243",
    name: "التفسير 2",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0244",
    name: "الفرائض",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0245",
    name: "مشروع التخرج",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0246",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0247",
    name: "القرآن الكريم 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0248",
    name: "اللغة الإنجليزية 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0249",
    name: "أصول الفقه",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0250",
    name: "الفقه 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0251",
    name: "الدراسات الأدبية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0252",
    name: "الدراسات النفسية والاجتماعية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0253",
    name: "التقنية الرقمية 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0254",
    name: "تطبيقات في القانون",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0255",
    name: "المواطنة الرقمية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0256",
    name: "المهارات الحياتية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0257",
    name: "البحث ومصادر المعلومات",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0258",
    name: "التربية الصحية والبدنية 2",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
  {
    id: "s_0259",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "شرعي",
  },
];

// المتوسطة (عام) | الصف الأول والثاني والثالث
export const excel_middle_general_grade1: Subject[] = [
  {
    id: "s_0260",
    name: "القرآن الكريم والدراسات الإسلامية",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
  {
    id: "s_0261",
    name: "اللغة العربية",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
  {
    id: "s_0262",
    name: "الدراسات الاجتماعية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
  {
    id: "s_0263",
    name: "الرياضيات",
    specializationIds: [],
    periodsPerClass: 6,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
  {
    id: "s_0264",
    name: "العلوم",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
  {
    id: "s_0265",
    name: "اللغة الإنجليزية",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
  {
    id: "s_0266",
    name: "المهارات الرقمية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
  {
    id: "s_0267",
    name: "التربية الفنية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
  {
    id: "s_0268",
    name: "التربية البدنية والدفاع عن النفس",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
  {
    id: "s_0269",
    name: "المهارات الحياتية والأسرية",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
  {
    id: "s_0270",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
];

// المتوسطة (عام) | الصف الثالث
export const excel_middle_general_grade3: Subject[] = [
  {
    id: "s_0271",
    name: "اللغة العربية",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
  {
    id: "s_0272",
    name: "الدراسات الاجتماعية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
  {
    id: "s_0273",
    name: "التفكير الناقد",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
  {
    id: "s_0274",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
];

// المتوسطة (تحفيظ) | الصف الأول والثاني
export const excel_middle_quran_grade1: Subject[] = [
  {
    id: "s_0275",
    name: "القرآن الكريم والدراسات الإسلامية",
    specializationIds: [],
    periodsPerClass: 8,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
  {
    id: "s_0276",
    name: "التجويد",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
  {
    id: "s_0277",
    name: "اللغة العربية",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
  {
    id: "s_0278",
    name: "الدراسات الاجتماعية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
  {
    id: "s_0279",
    name: "الرياضيات",
    specializationIds: [],
    periodsPerClass: 6,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
  {
    id: "s_0280",
    name: "العلوم",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
  {
    id: "s_0281",
    name: "اللغة الإنجليزية",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
  {
    id: "s_0282",
    name: "المهارات الرقمية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
  {
    id: "s_0283",
    name: "التربية الفنية",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
  {
    id: "s_0284",
    name: "التربية البدنية والدفاع عن النفس",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
  {
    id: "s_0285",
    name: "المهارات الحياتية والأسرية",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
];

// المتوسطة (تحفيظ) | الصف الثالث
export const excel_middle_quran_grade3: Subject[] = [
  {
    id: "s_0286",
    name: "القرآن الكريم والدراسات الإسلامية",
    specializationIds: [],
    periodsPerClass: 7,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
  {
    id: "s_0287",
    name: "التفكير الناقد",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
  {
    id: "s_0288",
    name: "اللغة العربية",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
];

export const EXCEL_1447_TEMPLATES = {
  'excel_elementary_general_grade1': excel_elementary_general_grade1,
  'excel_elementary_general_grade2': excel_elementary_general_grade2,
  'excel_elementary_general_grade3': excel_elementary_general_grade3,
  'excel_elementary_general_mixed': excel_elementary_general_mixed,
  'excel_elementary_general_upper': excel_elementary_general_upper,
  'excel_elementary_quran_grade1': excel_elementary_quran_grade1,
  'excel_elementary_quran_grade2': excel_elementary_quran_grade2,
  'excel_elementary_quran_grade3': excel_elementary_quran_grade3,
  'excel_elementary_quran_mixed': excel_elementary_quran_mixed,
  'excel_elementary_quran_upper': excel_elementary_quran_upper,
  'excel_high_y1_general_mixed': excel_high_y1_general_mixed,
  'excel_high_y2_cs_eng_mixed': excel_high_y2_cs_eng_mixed,
  'excel_high_y2_general_mixed': excel_high_y2_general_mixed,
  'excel_high_y2_islamic_mixed': excel_high_y2_islamic_mixed,
  'excel_high_y3_business_mixed': excel_high_y3_business_mixed,
  'excel_high_y3_cs_eng_mixed': excel_high_y3_cs_eng_mixed,
  'excel_high_y3_general_mixed': excel_high_y3_general_mixed,
  'excel_high_y3_health_mixed': excel_high_y3_health_mixed,
  'excel_high_y3_islamic_mixed': excel_high_y3_islamic_mixed,
  'excel_middle_general_grade1': excel_middle_general_grade1,
  'excel_middle_general_grade3': excel_middle_general_grade3,
  'excel_middle_quran_grade1': excel_middle_quran_grade1,
  'excel_middle_quran_grade3': excel_middle_quran_grade3,
};
