import { Phase, Subject } from './types';

export const GENERATED_TEMPLATES: Record<string, Subject[]> = {
  'excel_1447_elem_gen_الصف_الأول': [
    {
      id: 'excel_1447_elem_gen_الصف_الأول_1',
      name: 'اللغة الإنجليزية',
      specializationIds: ["5"],
      periodsPerClass: 3,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الأول_2',
      name: 'التربية الفنية',
      specializationIds: ["8"],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الأول_3',
      name: 'التربية البدنية والدفاع عن النفس',
      specializationIds: ["9"],
      periodsPerClass: 3,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الأول_4',
      name: 'المهارات الحياتية والأسرية',
      specializationIds: ["17"],
      periodsPerClass: 1,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الأول_5',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 3,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
  ],
  'excel_1447_elem_gen_الصف_الثاني': [
    {
      id: 'excel_1447_elem_gen_الصف_الثاني_1',
      name: 'اللغة الإنجليزية',
      specializationIds: ["5"],
      periodsPerClass: 3,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الثاني_2',
      name: 'التربية الفنية',
      specializationIds: ["8"],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الثاني_3',
      name: 'التربية البدنية والدفاع عن النفس',
      specializationIds: ["9"],
      periodsPerClass: 3,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الثاني_4',
      name: 'المهارات الحياتية والأسرية',
      specializationIds: ["17"],
      periodsPerClass: 1,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الثاني_5',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 3,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الثاني_6',
      name: 'القرآن الكريم والدراسات الإسلامية',
      specializationIds: ["1"],
      periodsPerClass: 5,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الثاني_7',
      name: 'اللغة العربية',
      specializationIds: ["2"],
      periodsPerClass: 7,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الثاني_8',
      name: 'الرياضيات',
      specializationIds: ["3"],
      periodsPerClass: 6,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
  ],
  'excel_1447_elem_gen_الصف_الثالث': [
    {
      id: 'excel_1447_elem_gen_الصف_الثالث_1',
      name: 'اللغة الإنجليزية',
      specializationIds: ["5"],
      periodsPerClass: 3,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الثالث_2',
      name: 'التربية الفنية',
      specializationIds: ["8"],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الثالث_3',
      name: 'التربية البدنية والدفاع عن النفس',
      specializationIds: ["9"],
      periodsPerClass: 3,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الثالث_4',
      name: 'المهارات الحياتية والأسرية',
      specializationIds: ["17"],
      periodsPerClass: 1,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الثالث_5',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 3,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الثالث_6',
      name: 'الرياضيات',
      specializationIds: ["3"],
      periodsPerClass: 6,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الثالث_7',
      name: 'اللغة العربية',
      specializationIds: ["2"],
      periodsPerClass: 6,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الثالث_8',
      name: 'العلوم',
      specializationIds: ["4"],
      periodsPerClass: 4,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
  ],
  'excel_1447_elem_gen_الصف_الرابع': [
    {
      id: 'excel_1447_elem_gen_الصف_الرابع_1',
      name: 'القرآن الكريم والدراسات الإسلامية',
      specializationIds: ["1"],
      periodsPerClass: 5,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الرابع_2',
      name: 'اللغة العربية',
      specializationIds: ["2"],
      periodsPerClass: 5,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الرابع_3',
      name: 'الدراسات الاجتماعية',
      specializationIds: ["6"],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الرابع_4',
      name: 'الرياضيات',
      specializationIds: ["3"],
      periodsPerClass: 6,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الرابع_5',
      name: 'العلوم',
      specializationIds: ["4"],
      periodsPerClass: 4,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الرابع_6',
      name: 'اللغة الإنجليزية',
      specializationIds: ["5"],
      periodsPerClass: 3,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الرابع_7',
      name: 'المهارات الرقمية',
      specializationIds: ["7"],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الرابع_8',
      name: 'التربية الفنية',
      specializationIds: ["8"],
      periodsPerClass: 1,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الرابع_9',
      name: 'التربية البدنية والدفاع عن النفس',
      specializationIds: ["9"],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الرابع_10',
      name: 'المهارات الحياتية والأسرية',
      specializationIds: ["17"],
      periodsPerClass: 1,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الرابع_11',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
  ],
  'excel_1447_elem_gen_الصف_الخامس': [
    {
      id: 'excel_1447_elem_gen_الصف_الخامس_1',
      name: 'القرآن الكريم والدراسات الإسلامية',
      specializationIds: ["1"],
      periodsPerClass: 5,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الخامس_2',
      name: 'اللغة العربية',
      specializationIds: ["2"],
      periodsPerClass: 5,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الخامس_3',
      name: 'الدراسات الاجتماعية',
      specializationIds: ["6"],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الخامس_4',
      name: 'الرياضيات',
      specializationIds: ["3"],
      periodsPerClass: 6,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الخامس_5',
      name: 'العلوم',
      specializationIds: ["4"],
      periodsPerClass: 4,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الخامس_6',
      name: 'اللغة الإنجليزية',
      specializationIds: ["5"],
      periodsPerClass: 3,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الخامس_7',
      name: 'المهارات الرقمية',
      specializationIds: ["7"],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الخامس_8',
      name: 'التربية الفنية',
      specializationIds: ["8"],
      periodsPerClass: 1,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الخامس_9',
      name: 'التربية البدنية والدفاع عن النفس',
      specializationIds: ["9"],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الخامس_10',
      name: 'المهارات الحياتية والأسرية',
      specializationIds: ["17"],
      periodsPerClass: 1,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_الخامس_11',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
  ],
  'excel_1447_elem_gen_الصف_السادس': [
    {
      id: 'excel_1447_elem_gen_الصف_السادس_1',
      name: 'القرآن الكريم والدراسات الإسلامية',
      specializationIds: ["1"],
      periodsPerClass: 5,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_السادس_2',
      name: 'اللغة العربية',
      specializationIds: ["2"],
      periodsPerClass: 5,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_السادس_3',
      name: 'الدراسات الاجتماعية',
      specializationIds: ["6"],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_السادس_4',
      name: 'الرياضيات',
      specializationIds: ["3"],
      periodsPerClass: 6,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_السادس_5',
      name: 'العلوم',
      specializationIds: ["4"],
      periodsPerClass: 4,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_السادس_6',
      name: 'اللغة الإنجليزية',
      specializationIds: ["5"],
      periodsPerClass: 3,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_السادس_7',
      name: 'المهارات الرقمية',
      specializationIds: ["7"],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_السادس_8',
      name: 'التربية الفنية',
      specializationIds: ["8"],
      periodsPerClass: 1,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_السادس_9',
      name: 'التربية البدنية والدفاع عن النفس',
      specializationIds: ["9"],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_السادس_10',
      name: 'المهارات الحياتية والأسرية',
      specializationIds: ["17"],
      periodsPerClass: 1,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
    {
      id: 'excel_1447_elem_gen_الصف_السادس_11',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'عام',
    },
  ],
  'excel_1447_elem_quran_الصف_الأول': [
    {
      id: 'excel_1447_elem_quran_الصف_الأول_1',
      name: 'القرآن الكريم والدراسات الإسلامية',
      specializationIds: ["1"],
      periodsPerClass: 9,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الأول_2',
      name: 'اللغة العربية',
      specializationIds: ["2"],
      periodsPerClass: 8,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الأول_3',
      name: 'الرياضيات',
      specializationIds: ["3"],
      periodsPerClass: 5,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الأول_4',
      name: 'العلوم',
      specializationIds: ["4"],
      periodsPerClass: 3,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الأول_5',
      name: 'اللغة الإنجليزية',
      specializationIds: ["5"],
      periodsPerClass: 3,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الأول_6',
      name: 'التربية الفنية',
      specializationIds: ["8"],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الأول_7',
      name: 'التربية البدنية والدفاع عن النفس',
      specializationIds: ["9"],
      periodsPerClass: 3,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الأول_8',
      name: 'المهارات الحياتية والأسرية',
      specializationIds: ["17"],
      periodsPerClass: 6,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الأول_9',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 1,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
  ],
  'excel_1447_elem_quran_الصف_الثاني': [
    {
      id: 'excel_1447_elem_quran_الصف_الثاني_1',
      name: 'القرآن الكريم والدراسات الإسلامية',
      specializationIds: ["1"],
      periodsPerClass: 9,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الثاني_2',
      name: 'العلوم',
      specializationIds: ["4"],
      periodsPerClass: 3,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الثاني_3',
      name: 'اللغة الإنجليزية',
      specializationIds: ["5"],
      periodsPerClass: 3,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الثاني_4',
      name: 'التربية الفنية',
      specializationIds: ["8"],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الثاني_5',
      name: 'التربية البدنية والدفاع عن النفس',
      specializationIds: ["9"],
      periodsPerClass: 3,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الثاني_6',
      name: 'المهارات الحياتية والأسرية',
      specializationIds: ["17"],
      periodsPerClass: 6,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الثاني_7',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 1,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الثاني_8',
      name: 'اللغة العربية',
      specializationIds: ["2"],
      periodsPerClass: 7,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الثاني_9',
      name: 'الرياضيات',
      specializationIds: ["3"],
      periodsPerClass: 6,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
  ],
  'excel_1447_elem_quran_الصف_الثالث': [
    {
      id: 'excel_1447_elem_quran_الصف_الثالث_1',
      name: 'القرآن الكريم والدراسات الإسلامية',
      specializationIds: ["1"],
      periodsPerClass: 9,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الثالث_2',
      name: 'اللغة الإنجليزية',
      specializationIds: ["5"],
      periodsPerClass: 3,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الثالث_3',
      name: 'التربية الفنية',
      specializationIds: ["8"],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الثالث_4',
      name: 'التربية البدنية والدفاع عن النفس',
      specializationIds: ["9"],
      periodsPerClass: 3,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الثالث_5',
      name: 'المهارات الحياتية والأسرية',
      specializationIds: ["17"],
      periodsPerClass: 6,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الثالث_6',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 1,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الثالث_7',
      name: 'الرياضيات',
      specializationIds: ["3"],
      periodsPerClass: 6,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الثالث_8',
      name: 'اللغة العربية',
      specializationIds: ["2"],
      periodsPerClass: 6,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الثالث_9',
      name: 'العلوم',
      specializationIds: ["4"],
      periodsPerClass: 4,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
  ],
  'excel_1447_elem_quran_الصف_الرابع': [
    {
      id: 'excel_1447_elem_quran_الصف_الرابع_1',
      name: 'القرآن الكريم والدراسات الإسلامية',
      specializationIds: ["1"],
      periodsPerClass: 8,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الرابع_2',
      name: 'التجويد',
      specializationIds: [],
      periodsPerClass: 1,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الرابع_3',
      name: 'اللغة العربية',
      specializationIds: ["2"],
      periodsPerClass: 5,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الرابع_4',
      name: 'الدراسات الاجتماعية',
      specializationIds: ["6"],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الرابع_5',
      name: 'الرياضيات',
      specializationIds: ["3"],
      periodsPerClass: 6,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الرابع_6',
      name: 'العلوم',
      specializationIds: ["4"],
      periodsPerClass: 4,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الرابع_7',
      name: 'اللغة الإنجليزية',
      specializationIds: ["5"],
      periodsPerClass: 3,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الرابع_8',
      name: 'المهارات الرقمية',
      specializationIds: ["7"],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الرابع_9',
      name: 'التربية الفنية',
      specializationIds: ["8"],
      periodsPerClass: 1,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الرابع_10',
      name: 'التربية البدنية والدفاع عن النفس',
      specializationIds: ["9"],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الرابع_11',
      name: 'المهارات الحياتية والأسرية',
      specializationIds: ["17"],
      periodsPerClass: 1,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
  ],
  'excel_1447_elem_quran_الصف_الخامس': [
    {
      id: 'excel_1447_elem_quran_الصف_الخامس_1',
      name: 'القرآن الكريم والدراسات الإسلامية',
      specializationIds: ["1"],
      periodsPerClass: 8,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الخامس_2',
      name: 'التجويد',
      specializationIds: [],
      periodsPerClass: 1,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الخامس_3',
      name: 'اللغة العربية',
      specializationIds: ["2"],
      periodsPerClass: 5,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الخامس_4',
      name: 'الدراسات الاجتماعية',
      specializationIds: ["6"],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الخامس_5',
      name: 'الرياضيات',
      specializationIds: ["3"],
      periodsPerClass: 6,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الخامس_6',
      name: 'العلوم',
      specializationIds: ["4"],
      periodsPerClass: 4,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الخامس_7',
      name: 'اللغة الإنجليزية',
      specializationIds: ["5"],
      periodsPerClass: 3,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الخامس_8',
      name: 'المهارات الرقمية',
      specializationIds: ["7"],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الخامس_9',
      name: 'التربية الفنية',
      specializationIds: ["8"],
      periodsPerClass: 1,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الخامس_10',
      name: 'التربية البدنية والدفاع عن النفس',
      specializationIds: ["9"],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_الخامس_11',
      name: 'المهارات الحياتية والأسرية',
      specializationIds: ["17"],
      periodsPerClass: 1,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
  ],
  'excel_1447_elem_quran_الصف_السادس': [
    {
      id: 'excel_1447_elem_quran_الصف_السادس_1',
      name: 'القرآن الكريم والدراسات الإسلامية',
      specializationIds: ["1"],
      periodsPerClass: 8,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_السادس_2',
      name: 'التجويد',
      specializationIds: [],
      periodsPerClass: 1,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_السادس_3',
      name: 'اللغة العربية',
      specializationIds: ["2"],
      periodsPerClass: 5,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_السادس_4',
      name: 'الدراسات الاجتماعية',
      specializationIds: ["6"],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_السادس_5',
      name: 'الرياضيات',
      specializationIds: ["3"],
      periodsPerClass: 6,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_السادس_6',
      name: 'العلوم',
      specializationIds: ["4"],
      periodsPerClass: 4,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_السادس_7',
      name: 'اللغة الإنجليزية',
      specializationIds: ["5"],
      periodsPerClass: 3,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_السادس_8',
      name: 'المهارات الرقمية',
      specializationIds: ["7"],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_السادس_9',
      name: 'التربية الفنية',
      specializationIds: ["8"],
      periodsPerClass: 1,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_السادس_10',
      name: 'التربية البدنية والدفاع عن النفس',
      specializationIds: ["9"],
      periodsPerClass: 2,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_elem_quran_الصف_السادس_11',
      name: 'المهارات الحياتية والأسرية',
      specializationIds: ["17"],
      periodsPerClass: 1,
      phases: [Phase.ELEMENTARY],
      department: 'تحفيظ',
    },
  ],
  'excel_1447_mid_gen_الصف_الأول': [
    {
      id: 'excel_1447_mid_gen_الصف_الأول_1',
      name: 'القرآن الكريم والدراسات الإسلامية',
      specializationIds: ["1"],
      periodsPerClass: 5,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الأول_2',
      name: 'اللغة العربية',
      specializationIds: ["2"],
      periodsPerClass: 5,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الأول_3',
      name: 'الدراسات الاجتماعية',
      specializationIds: ["6"],
      periodsPerClass: 3,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الأول_4',
      name: 'الرياضيات',
      specializationIds: ["3"],
      periodsPerClass: 6,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الأول_5',
      name: 'العلوم',
      specializationIds: ["4"],
      periodsPerClass: 4,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الأول_6',
      name: 'اللغة الإنجليزية',
      specializationIds: ["5"],
      periodsPerClass: 4,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الأول_7',
      name: 'المهارات الرقمية',
      specializationIds: ["7"],
      periodsPerClass: 2,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الأول_8',
      name: 'التربية الفنية',
      specializationIds: ["8"],
      periodsPerClass: 2,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الأول_9',
      name: 'التربية البدنية والدفاع عن النفس',
      specializationIds: ["9"],
      periodsPerClass: 2,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الأول_10',
      name: 'المهارات الحياتية والأسرية',
      specializationIds: ["17"],
      periodsPerClass: 1,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الأول_11',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 1,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الأول_12',
      name: 'التفكير الناقد',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
  ],
  'excel_1447_mid_gen_الصف_الثاني': [
    {
      id: 'excel_1447_mid_gen_الصف_الثاني_1',
      name: 'القرآن الكريم والدراسات الإسلامية',
      specializationIds: ["1"],
      periodsPerClass: 5,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الثاني_2',
      name: 'اللغة العربية',
      specializationIds: ["2"],
      periodsPerClass: 5,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الثاني_3',
      name: 'الدراسات الاجتماعية',
      specializationIds: ["6"],
      periodsPerClass: 3,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الثاني_4',
      name: 'الرياضيات',
      specializationIds: ["3"],
      periodsPerClass: 6,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الثاني_5',
      name: 'العلوم',
      specializationIds: ["4"],
      periodsPerClass: 4,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الثاني_6',
      name: 'اللغة الإنجليزية',
      specializationIds: ["5"],
      periodsPerClass: 4,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الثاني_7',
      name: 'المهارات الرقمية',
      specializationIds: ["7"],
      periodsPerClass: 2,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الثاني_8',
      name: 'التربية الفنية',
      specializationIds: ["8"],
      periodsPerClass: 2,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الثاني_9',
      name: 'التربية البدنية والدفاع عن النفس',
      specializationIds: ["9"],
      periodsPerClass: 2,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الثاني_10',
      name: 'المهارات الحياتية والأسرية',
      specializationIds: ["17"],
      periodsPerClass: 1,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الثاني_11',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 1,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الثاني_12',
      name: 'التفكير الناقد',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
  ],
  'excel_1447_mid_gen_الصف_الثالث': [
    {
      id: 'excel_1447_mid_gen_الصف_الثالث_1',
      name: 'القرآن الكريم والدراسات الإسلامية',
      specializationIds: ["1"],
      periodsPerClass: 5,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الثالث_2',
      name: 'الرياضيات',
      specializationIds: ["3"],
      periodsPerClass: 6,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الثالث_3',
      name: 'العلوم',
      specializationIds: ["4"],
      periodsPerClass: 4,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الثالث_4',
      name: 'اللغة الإنجليزية',
      specializationIds: ["5"],
      periodsPerClass: 4,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الثالث_5',
      name: 'المهارات الرقمية',
      specializationIds: ["7"],
      periodsPerClass: 2,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الثالث_6',
      name: 'التربية الفنية',
      specializationIds: ["8"],
      periodsPerClass: 2,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الثالث_7',
      name: 'التربية البدنية والدفاع عن النفس',
      specializationIds: ["9"],
      periodsPerClass: 2,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الثالث_8',
      name: 'المهارات الحياتية والأسرية',
      specializationIds: ["17"],
      periodsPerClass: 1,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الثالث_9',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 1,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الثالث_10',
      name: 'اللغة العربية',
      specializationIds: ["2"],
      periodsPerClass: 4,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الثالث_11',
      name: 'الدراسات الاجتماعية',
      specializationIds: ["6"],
      periodsPerClass: 2,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الثالث_12',
      name: 'التفكير الناقد',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
    {
      id: 'excel_1447_mid_gen_الصف_الثالث_13',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 1,
      phases: [Phase.MIDDLE],
      department: 'عام',
    },
  ],
  'excel_1447_mid_quran_الصف_الأول': [
    {
      id: 'excel_1447_mid_quran_الصف_الأول_1',
      name: 'القرآن الكريم والدراسات الإسلامية',
      specializationIds: ["1"],
      periodsPerClass: 8,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الأول_2',
      name: 'التجويد',
      specializationIds: [],
      periodsPerClass: 1,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الأول_3',
      name: 'اللغة العربية',
      specializationIds: ["2"],
      periodsPerClass: 5,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الأول_4',
      name: 'الدراسات الاجتماعية',
      specializationIds: ["6"],
      periodsPerClass: 2,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الأول_5',
      name: 'الرياضيات',
      specializationIds: ["3"],
      periodsPerClass: 6,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الأول_6',
      name: 'العلوم',
      specializationIds: ["4"],
      periodsPerClass: 4,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الأول_7',
      name: 'اللغة الإنجليزية',
      specializationIds: ["5"],
      periodsPerClass: 4,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الأول_8',
      name: 'المهارات الرقمية',
      specializationIds: ["7"],
      periodsPerClass: 2,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الأول_9',
      name: 'التربية الفنية',
      specializationIds: ["8"],
      periodsPerClass: 1,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الأول_10',
      name: 'التربية البدنية والدفاع عن النفس',
      specializationIds: ["9"],
      periodsPerClass: 1,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الأول_11',
      name: 'المهارات الحياتية والأسرية',
      specializationIds: ["17"],
      periodsPerClass: 1,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
  ],
  'excel_1447_mid_quran_الصف_الثاني': [
    {
      id: 'excel_1447_mid_quran_الصف_الثاني_1',
      name: 'القرآن الكريم والدراسات الإسلامية',
      specializationIds: ["1"],
      periodsPerClass: 8,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الثاني_2',
      name: 'التجويد',
      specializationIds: [],
      periodsPerClass: 1,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الثاني_3',
      name: 'اللغة العربية',
      specializationIds: ["2"],
      periodsPerClass: 5,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الثاني_4',
      name: 'الدراسات الاجتماعية',
      specializationIds: ["6"],
      periodsPerClass: 2,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الثاني_5',
      name: 'الرياضيات',
      specializationIds: ["3"],
      periodsPerClass: 6,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الثاني_6',
      name: 'العلوم',
      specializationIds: ["4"],
      periodsPerClass: 4,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الثاني_7',
      name: 'اللغة الإنجليزية',
      specializationIds: ["5"],
      periodsPerClass: 4,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الثاني_8',
      name: 'المهارات الرقمية',
      specializationIds: ["7"],
      periodsPerClass: 2,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الثاني_9',
      name: 'التربية الفنية',
      specializationIds: ["8"],
      periodsPerClass: 1,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الثاني_10',
      name: 'التربية البدنية والدفاع عن النفس',
      specializationIds: ["9"],
      periodsPerClass: 1,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الثاني_11',
      name: 'المهارات الحياتية والأسرية',
      specializationIds: ["17"],
      periodsPerClass: 1,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
  ],
  'excel_1447_mid_quran_الصف_الثالث': [
    {
      id: 'excel_1447_mid_quran_الصف_الثالث_1',
      name: 'التجويد',
      specializationIds: [],
      periodsPerClass: 1,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الثالث_2',
      name: 'الدراسات الاجتماعية',
      specializationIds: ["6"],
      periodsPerClass: 2,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الثالث_3',
      name: 'الرياضيات',
      specializationIds: ["3"],
      periodsPerClass: 6,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الثالث_4',
      name: 'العلوم',
      specializationIds: ["4"],
      periodsPerClass: 4,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الثالث_5',
      name: 'اللغة الإنجليزية',
      specializationIds: ["5"],
      periodsPerClass: 4,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الثالث_6',
      name: 'المهارات الرقمية',
      specializationIds: ["7"],
      periodsPerClass: 2,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الثالث_7',
      name: 'التربية الفنية',
      specializationIds: ["8"],
      periodsPerClass: 1,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الثالث_8',
      name: 'التربية البدنية والدفاع عن النفس',
      specializationIds: ["9"],
      periodsPerClass: 1,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الثالث_9',
      name: 'المهارات الحياتية والأسرية',
      specializationIds: ["17"],
      periodsPerClass: 1,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الثالث_10',
      name: 'القرآن الكريم والدراسات الإسلامية',
      specializationIds: ["1"],
      periodsPerClass: 7,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الثالث_11',
      name: 'التفكير الناقد',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
    {
      id: 'excel_1447_mid_quran_الصف_الثالث_12',
      name: 'اللغة العربية',
      specializationIds: ["2"],
      periodsPerClass: 4,
      phases: [Phase.MIDDLE],
      department: 'تحفيظ',
    },
  ],
  'excel_1447_high_grade_1_pathway_مشترك_sem_1': [
    {
      id: 'excel_1447_high_grade_1_pathway_مشترك_sem_1_1',
      name: 'القرآن الكريم وتفسيره',
      specializationIds: ["1"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'مشترك',
    },
    {
      id: 'excel_1447_high_grade_1_pathway_مشترك_sem_1_2',
      name: 'الرياضيات 1',
      specializationIds: ["3"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'مشترك',
    },
    {
      id: 'excel_1447_high_grade_1_pathway_مشترك_sem_1_3',
      name: 'اللغة الإنجليزية 1',
      specializationIds: ["5"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'مشترك',
    },
    {
      id: 'excel_1447_high_grade_1_pathway_مشترك_sem_1_4',
      name: 'التقنية الرقمية 1',
      specializationIds: ["7"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'مشترك',
    },
    {
      id: 'excel_1447_high_grade_1_pathway_مشترك_sem_1_5',
      name: 'الكفايات اللغوية 1',
      specializationIds: ["2"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'مشترك',
    },
    {
      id: 'excel_1447_high_grade_1_pathway_مشترك_sem_1_6',
      name: 'مادة العلوم (كيمياء/فيزياء)',
      specializationIds: ["12"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'مشترك',
    },
    {
      id: 'excel_1447_high_grade_1_pathway_مشترك_sem_1_7',
      name: 'التفكير الناقد',
      specializationIds: [],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'مشترك',
    },
    {
      id: 'excel_1447_high_grade_1_pathway_مشترك_sem_1_8',
      name: 'التربية الصحية والبدنية 1',
      specializationIds: ["9"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'مشترك',
    },
  ],
  'excel_1447_high_grade_1_pathway_مشترك_sem_2': [
    {
      id: 'excel_1447_high_grade_1_pathway_مشترك_sem_2_1',
      name: 'الرياضيات 1',
      specializationIds: ["3"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'مشترك',
    },
    {
      id: 'excel_1447_high_grade_1_pathway_مشترك_sem_2_2',
      name: 'اللغة الإنجليزية 1',
      specializationIds: ["5"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'مشترك',
    },
    {
      id: 'excel_1447_high_grade_1_pathway_مشترك_sem_2_3',
      name: 'التقنية الرقمية 1',
      specializationIds: ["7"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'مشترك',
    },
    {
      id: 'excel_1447_high_grade_1_pathway_مشترك_sem_2_4',
      name: 'الأحياء 1',
      specializationIds: ["11"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'مشترك',
    },
    {
      id: 'excel_1447_high_grade_1_pathway_مشترك_sem_2_5',
      name: 'مادة العلوم (كيمياء/فيزياء)',
      specializationIds: ["12"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'مشترك',
    },
    {
      id: 'excel_1447_high_grade_1_pathway_مشترك_sem_2_6',
      name: 'الكفايات اللغوية 1',
      specializationIds: ["2"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'مشترك',
    },
    {
      id: 'excel_1447_high_grade_1_pathway_مشترك_sem_2_7',
      name: 'علم البيئة',
      specializationIds: ["4"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'مشترك',
    },
    {
      id: 'excel_1447_high_grade_1_pathway_مشترك_sem_2_8',
      name: 'الحديث 1',
      specializationIds: ["1"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'مشترك',
    },
    {
      id: 'excel_1447_high_grade_1_pathway_مشترك_sem_2_9',
      name: 'المعرفة المالية',
      specializationIds: ["13"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'مشترك',
    },
    {
      id: 'excel_1447_high_grade_1_pathway_مشترك_sem_2_10',
      name: 'الدراسات الاجتماعية',
      specializationIds: ["6"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'مشترك',
    },
    {
      id: 'excel_1447_high_grade_1_pathway_مشترك_sem_2_11',
      name: 'التربية المهنية',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'مشترك',
    },
    {
      id: 'excel_1447_high_grade_1_pathway_مشترك_sem_2_12',
      name: 'التربية الصحية والبدنية 1',
      specializationIds: ["9"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'مشترك',
    },
  ],
  'excel_1447_high_grade_2_pathway_عام_sem_1': [
    {
      id: 'excel_1447_high_grade_2_pathway_عام_sem_1_1',
      name: 'الرياضيات 2',
      specializationIds: ["3"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_عام_sem_1_2',
      name: 'اللغة الإنجليزية 2',
      specializationIds: ["5"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_عام_sem_1_3',
      name: 'الفيزياء 2',
      specializationIds: ["12"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_عام_sem_1_4',
      name: 'الكيمياء 2',
      specializationIds: ["10"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_عام_sem_1_5',
      name: 'الأحياء 2',
      specializationIds: ["11"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_عام_sem_1_6',
      name: 'الكفايات اللغوية 2',
      specializationIds: ["2"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_عام_sem_1_7',
      name: 'التاريخ',
      specializationIds: ["6"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_عام_sem_1_8',
      name: 'اللياقة والثقافة الصحية',
      specializationIds: ["9"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_عام_sem_1_9',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'عام',
    },
  ],
  'excel_1447_high_grade_2_pathway_عام_sem_2': [
    {
      id: 'excel_1447_high_grade_2_pathway_عام_sem_2_1',
      name: 'الرياضيات 2',
      specializationIds: ["3"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_عام_sem_2_2',
      name: 'اللغة الإنجليزية 2',
      specializationIds: ["5"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_عام_sem_2_3',
      name: 'الكيمياء 2',
      specializationIds: ["10"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_عام_sem_2_4',
      name: 'الأحياء 2',
      specializationIds: ["11"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_عام_sem_2_5',
      name: 'التقنية الرقمية 2',
      specializationIds: ["7"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_عام_sem_2_6',
      name: 'التوحيد 1',
      specializationIds: ["1"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_عام_sem_2_7',
      name: 'الجغرافيا',
      specializationIds: ["6"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_عام_sem_2_8',
      name: 'الفنون',
      specializationIds: ["8"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_عام_sem_2_9',
      name: 'اللياقة والثقافة الصحية',
      specializationIds: ["9"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_عام_sem_2_10',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'عام',
    },
  ],
  'excel_1447_high_grade_2_pathway_حاسب_وهندسة_sem_1': [
    {
      id: 'excel_1447_high_grade_2_pathway_حاسب_وهندسة_sem_1_1',
      name: 'الرياضيات 2',
      specializationIds: ["3"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_حاسب_وهندسة_sem_1_2',
      name: 'اللغة الإنجليزية 2',
      specializationIds: ["5"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_حاسب_وهندسة_sem_1_3',
      name: 'الفيزياء 2',
      specializationIds: ["12"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_حاسب_وهندسة_sem_1_4',
      name: 'إنترنت الأشياء 1-1',
      specializationIds: ["7"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_حاسب_وهندسة_sem_1_5',
      name: 'الكفايات اللغوية 2',
      specializationIds: ["2"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_حاسب_وهندسة_sem_1_6',
      name: 'التاريخ',
      specializationIds: ["6"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_حاسب_وهندسة_sem_1_7',
      name: 'اللياقة والثقافة الصحية',
      specializationIds: ["9"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_حاسب_وهندسة_sem_1_8',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
  ],
  'excel_1447_high_grade_2_pathway_حاسب_وهندسة_sem_2': [
    {
      id: 'excel_1447_high_grade_2_pathway_حاسب_وهندسة_sem_2_1',
      name: 'الرياضيات 2',
      specializationIds: ["3"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_حاسب_وهندسة_sem_2_2',
      name: 'اللغة الإنجليزية 2',
      specializationIds: ["5"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_حاسب_وهندسة_sem_2_3',
      name: 'الكيمياء 2',
      specializationIds: ["10"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_حاسب_وهندسة_sem_2_4',
      name: 'علم البيانات',
      specializationIds: ["7"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_حاسب_وهندسة_sem_2_5',
      name: 'الهندسة',
      specializationIds: ["22"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_حاسب_وهندسة_sem_2_6',
      name: 'التوحيد 1',
      specializationIds: ["1"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_حاسب_وهندسة_sem_2_7',
      name: 'الجغرافيا',
      specializationIds: ["6"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_حاسب_وهندسة_sem_2_8',
      name: 'اللياقة والثقافة الصحية',
      specializationIds: ["9"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_حاسب_وهندسة_sem_2_9',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
  ],
  'excel_1447_high_grade_2_pathway_صحة_وحياة_sem_1': [
    {
      id: 'excel_1447_high_grade_2_pathway_صحة_وحياة_sem_1_1',
      name: 'الرياضيات 2',
      specializationIds: ["3"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_صحة_وحياة_sem_1_2',
      name: 'اللغة الإنجليزية 2',
      specializationIds: ["5"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_صحة_وحياة_sem_1_3',
      name: 'الكيمياء 2',
      specializationIds: ["10"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_صحة_وحياة_sem_1_4',
      name: 'الأحياء 2',
      specializationIds: ["11"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_صحة_وحياة_sem_1_5',
      name: 'مبادئ العلوم الصحية',
      specializationIds: ["4"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_صحة_وحياة_sem_1_6',
      name: 'الكفايات اللغوية 2',
      specializationIds: ["2"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_صحة_وحياة_sem_1_7',
      name: 'اللياقة والثقافة الصحية',
      specializationIds: ["9"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_صحة_وحياة_sem_1_8',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
  ],
  'excel_1447_high_grade_2_pathway_صحة_وحياة_sem_2': [
    {
      id: 'excel_1447_high_grade_2_pathway_صحة_وحياة_sem_2_1',
      name: 'الرياضيات 2',
      specializationIds: ["3"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_صحة_وحياة_sem_2_2',
      name: 'اللغة الإنجليزية 2',
      specializationIds: ["5"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_صحة_وحياة_sem_2_3',
      name: 'الفيزياء 2',
      specializationIds: ["12"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_صحة_وحياة_sem_2_4',
      name: 'الرعاية الصحية',
      specializationIds: [],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_صحة_وحياة_sem_2_5',
      name: 'التقنية الرقمية 2',
      specializationIds: ["7"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_صحة_وحياة_sem_2_6',
      name: 'التوحيد 1',
      specializationIds: ["1"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_صحة_وحياة_sem_2_7',
      name: 'اللياقة والثقافة الصحية',
      specializationIds: ["9"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_صحة_وحياة_sem_2_8',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
  ],
  'excel_1447_high_grade_2_pathway_إدارة_أعمال_sem_1': [
    {
      id: 'excel_1447_high_grade_2_pathway_إدارة_أعمال_sem_1_1',
      name: 'اللغة الإنجليزية 2',
      specializationIds: ["5"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_إدارة_أعمال_sem_1_2',
      name: 'صناعة القرار في الأعمال',
      specializationIds: ["13"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_إدارة_أعمال_sem_1_3',
      name: 'مقدمة في الأعمال',
      specializationIds: ["13"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_إدارة_أعمال_sem_1_4',
      name: 'الكفايات اللغوية 2',
      specializationIds: ["2"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_إدارة_أعمال_sem_1_5',
      name: 'الإدارة المالية',
      specializationIds: ["13"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_إدارة_أعمال_sem_1_6',
      name: 'التوحيد 1',
      specializationIds: ["1"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_إدارة_أعمال_sem_1_7',
      name: 'التاريخ',
      specializationIds: ["6"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_إدارة_أعمال_sem_1_8',
      name: 'اللياقة والثقافة الصحية',
      specializationIds: ["9"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_إدارة_أعمال_sem_1_9',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
  ],
  'excel_1447_high_grade_2_pathway_إدارة_أعمال_sem_2': [
    {
      id: 'excel_1447_high_grade_2_pathway_إدارة_أعمال_sem_2_1',
      name: 'اللغة الإنجليزية 2',
      specializationIds: ["5"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_إدارة_أعمال_sem_2_2',
      name: 'صناعة القرار في الأعمال',
      specializationIds: ["13"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_إدارة_أعمال_sem_2_3',
      name: 'مقدمة في الأعمال',
      specializationIds: ["13"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_إدارة_أعمال_sem_2_4',
      name: 'مبادئ الاقتصاد',
      specializationIds: ["13"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_إدارة_أعمال_sem_2_5',
      name: 'مبادئ الإدارة',
      specializationIds: ["13"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_إدارة_أعمال_sem_2_6',
      name: 'التفسير 1',
      specializationIds: ["1"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_إدارة_أعمال_sem_2_7',
      name: 'الجغرافيا',
      specializationIds: ["6"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_إدارة_أعمال_sem_2_8',
      name: 'الفنون',
      specializationIds: ["8"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_إدارة_أعمال_sem_2_9',
      name: 'اللياقة والثقافة الصحية',
      specializationIds: ["9"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_إدارة_أعمال_sem_2_10',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
  ],
  'excel_1447_high_grade_2_pathway_شرعي_sem_1': [
    {
      id: 'excel_1447_high_grade_2_pathway_شرعي_sem_1_1',
      name: 'القرآن الكريم 1',
      specializationIds: ["1"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_شرعي_sem_1_2',
      name: 'اللغة الإنجليزية 2',
      specializationIds: ["5"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_شرعي_sem_1_3',
      name: 'الكفايات اللغوية 2',
      specializationIds: ["2"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_شرعي_sem_1_4',
      name: 'القراءات 1',
      specializationIds: [],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_شرعي_sem_1_5',
      name: 'الحديث 2',
      specializationIds: ["1"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_شرعي_sem_1_6',
      name: 'التوحيد 1',
      specializationIds: ["1"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_شرعي_sem_1_7',
      name: 'التاريخ',
      specializationIds: ["6"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_شرعي_sem_1_8',
      name: 'اللياقة والثقافة الصحية',
      specializationIds: ["9"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_شرعي_sem_1_9',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
  ],
  'excel_1447_high_grade_2_pathway_شرعي_sem_2': [
    {
      id: 'excel_1447_high_grade_2_pathway_شرعي_sem_2_1',
      name: 'القرآن الكريم 1',
      specializationIds: ["1"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_شرعي_sem_2_2',
      name: 'اللغة الإنجليزية 2',
      specializationIds: ["5"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_شرعي_sem_2_3',
      name: 'علوم القرآن',
      specializationIds: ["1"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_شرعي_sem_2_4',
      name: 'القراءات 2',
      specializationIds: [],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_شرعي_sem_2_5',
      name: 'مصطلح الحديث',
      specializationIds: ["1"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_شرعي_sem_2_6',
      name: 'التوحيد 2',
      specializationIds: ["1"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_شرعي_sem_2_7',
      name: 'الجغرافيا',
      specializationIds: ["6"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_شرعي_sem_2_8',
      name: 'الفنون',
      specializationIds: ["8"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_شرعي_sem_2_9',
      name: 'اللياقة والثقافة الصحية',
      specializationIds: ["9"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_2_pathway_شرعي_sem_2_10',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
  ],
  'excel_1447_high_grade_3_pathway_عام_sem_1': [
    {
      id: 'excel_1447_high_grade_3_pathway_عام_sem_1_1',
      name: 'الرياضيات 3',
      specializationIds: ["3"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_عام_sem_1_2',
      name: 'اللغة الإنجليزية 3',
      specializationIds: ["5"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_عام_sem_1_3',
      name: 'الفيزياء 3',
      specializationIds: ["12"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_عام_sem_1_4',
      name: 'الكيمياء 3',
      specializationIds: ["10"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_عام_sem_1_5',
      name: 'الأحياء 3',
      specializationIds: ["11"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_عام_sem_1_6',
      name: 'علوم الأرض والفضاء',
      specializationIds: ["20"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_عام_sem_1_7',
      name: 'المجال الاختياري',
      specializationIds: [],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_عام_sem_1_8',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 1,
      phases: [Phase.HIGH],
      department: 'عام',
    },
  ],
  'excel_1447_high_grade_3_pathway_عام_sem_2': [
    {
      id: 'excel_1447_high_grade_3_pathway_عام_sem_2_1',
      name: 'الرياضيات 3',
      specializationIds: ["3"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_عام_sem_2_2',
      name: 'اللغة الإنجليزية 3',
      specializationIds: ["5"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_عام_sem_2_3',
      name: 'الفيزياء 3',
      specializationIds: ["12"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_عام_sem_2_4',
      name: 'الكيمياء 3',
      specializationIds: ["10"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_عام_sem_2_5',
      name: 'الأحياء 3',
      specializationIds: ["11"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_عام_sem_2_6',
      name: 'علوم الأرض والفضاء',
      specializationIds: ["20"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_عام_sem_2_7',
      name: 'الفقه 1',
      specializationIds: ["1"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_عام_sem_2_8',
      name: 'الدراسات الأدبية',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_عام_sem_2_9',
      name: 'الدراسات النفسية والاجتماعية',
      specializationIds: ["6"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_عام_sem_2_10',
      name: 'التقنية الرقمية 3',
      specializationIds: ["7"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_عام_sem_2_11',
      name: 'المواطنة الرقمية',
      specializationIds: ["7"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_عام_sem_2_12',
      name: 'المجال الاختياري',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'عام',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_عام_sem_2_13',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'عام',
    },
  ],
  'excel_1447_high_grade_3_pathway_حاسب_وهندسة_sem_1': [
    {
      id: 'excel_1447_high_grade_3_pathway_حاسب_وهندسة_sem_1_1',
      name: 'الرياضيات 3',
      specializationIds: ["3"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_حاسب_وهندسة_sem_1_2',
      name: 'اللغة الإنجليزية 3',
      specializationIds: ["5"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_حاسب_وهندسة_sem_1_3',
      name: 'الفيزياء 3',
      specializationIds: ["12"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_حاسب_وهندسة_sem_1_4',
      name: 'الكيمياء 3',
      specializationIds: ["10"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_حاسب_وهندسة_sem_1_5',
      name: 'علوم الأرض والفضاء',
      specializationIds: ["20"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_حاسب_وهندسة_sem_1_6',
      name: 'الذكاء الاصطناعي',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_حاسب_وهندسة_sem_1_7',
      name: 'هندسة البرمجيات',
      specializationIds: ["22"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_حاسب_وهندسة_sem_1_8',
      name: 'التربية الصحية والبدنية 2',
      specializationIds: ["9"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_حاسب_وهندسة_sem_1_9',
      name: 'مشروع التخرج',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_حاسب_وهندسة_sem_1_10',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 1,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
  ],
  'excel_1447_high_grade_3_pathway_حاسب_وهندسة_sem_2': [
    {
      id: 'excel_1447_high_grade_3_pathway_حاسب_وهندسة_sem_2_1',
      name: 'الرياضيات 3',
      specializationIds: ["3"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_حاسب_وهندسة_sem_2_2',
      name: 'اللغة الإنجليزية 3',
      specializationIds: ["5"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_حاسب_وهندسة_sem_2_3',
      name: 'الأمن السيبراني',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_حاسب_وهندسة_sem_2_4',
      name: 'التصميم الهندسي',
      specializationIds: [],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_حاسب_وهندسة_sem_2_5',
      name: 'الفقه 1',
      specializationIds: ["1"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_حاسب_وهندسة_sem_2_6',
      name: 'المهارات الحياتية',
      specializationIds: ["17"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_حاسب_وهندسة_sem_2_7',
      name: 'البحث ومصادر المعلومات',
      specializationIds: ["4"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_حاسب_وهندسة_sem_2_8',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'حاسب وهندسة',
    },
  ],
  'excel_1447_high_grade_3_pathway_صحة_وحياة_sem_1': [
    {
      id: 'excel_1447_high_grade_3_pathway_صحة_وحياة_sem_1_1',
      name: 'الرياضيات 3',
      specializationIds: ["3"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_صحة_وحياة_sem_1_2',
      name: 'اللغة الإنجليزية 3',
      specializationIds: ["5"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_صحة_وحياة_sem_1_3',
      name: 'الأحياء 3',
      specializationIds: ["11"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_صحة_وحياة_sem_1_4',
      name: 'أنظمة جسم الإنسان',
      specializationIds: [],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_صحة_وحياة_sem_1_5',
      name: 'علوم الأرض والفضاء',
      specializationIds: ["20"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_صحة_وحياة_sem_1_6',
      name: 'المهارات الحياتية',
      specializationIds: ["17"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_صحة_وحياة_sem_1_7',
      name: 'التربية الصحية والبدنية 2',
      specializationIds: ["9"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_صحة_وحياة_sem_1_8',
      name: 'مشروع التخرج',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_صحة_وحياة_sem_1_9',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
  ],
  'excel_1447_high_grade_3_pathway_صحة_وحياة_sem_2': [
    {
      id: 'excel_1447_high_grade_3_pathway_صحة_وحياة_sem_2_1',
      name: 'الرياضيات 3',
      specializationIds: ["3"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_صحة_وحياة_sem_2_2',
      name: 'اللغة الإنجليزية 3',
      specializationIds: ["5"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_صحة_وحياة_sem_2_3',
      name: 'الفيزياء 3',
      specializationIds: ["12"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_صحة_وحياة_sem_2_4',
      name: 'الكيمياء 3',
      specializationIds: ["10"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_صحة_وحياة_sem_2_5',
      name: 'الفقه 1',
      specializationIds: ["1"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_صحة_وحياة_sem_2_6',
      name: 'الإحصاء',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_صحة_وحياة_sem_2_7',
      name: 'البحث ومصادر المعلومات',
      specializationIds: ["4"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_صحة_وحياة_sem_2_8',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 1,
      phases: [Phase.HIGH],
      department: 'صحة وحياة',
    },
  ],
  'excel_1447_high_grade_3_pathway_إدارة_أعمال_sem_1': [
    {
      id: 'excel_1447_high_grade_3_pathway_إدارة_أعمال_sem_1_1',
      name: 'اللغة الإنجليزية 3',
      specializationIds: ["5"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_إدارة_أعمال_sem_1_2',
      name: 'إدارة الفعاليات',
      specializationIds: ["13"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_إدارة_أعمال_sem_1_3',
      name: 'تخطيط الحملات التسويقية',
      specializationIds: [],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_إدارة_أعمال_sem_1_4',
      name: 'مبادئ القانون',
      specializationIds: [],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_إدارة_أعمال_sem_1_5',
      name: 'الدراسات البلاغية والنقدية',
      specializationIds: [],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_إدارة_أعمال_sem_1_6',
      name: 'الإحصاء',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_إدارة_أعمال_sem_1_7',
      name: 'التربية الصحية والبدنية 2',
      specializationIds: ["9"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_إدارة_أعمال_sem_1_8',
      name: 'البحث ومصادر المعلومات',
      specializationIds: ["4"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_إدارة_أعمال_sem_1_9',
      name: 'مشروع التخرج',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_إدارة_أعمال_sem_1_10',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 1,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
  ],
  'excel_1447_high_grade_3_pathway_إدارة_أعمال_sem_2': [
    {
      id: 'excel_1447_high_grade_3_pathway_إدارة_أعمال_sem_2_1',
      name: 'اللغة الإنجليزية 3',
      specializationIds: ["5"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_إدارة_أعمال_sem_2_2',
      name: 'إدارة الفعاليات',
      specializationIds: ["13"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_إدارة_أعمال_sem_2_3',
      name: 'تخطيط الحملات التسويقية',
      specializationIds: [],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_إدارة_أعمال_sem_2_4',
      name: 'السكرتارية والإدارة المكتبية',
      specializationIds: ["13"],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_إدارة_أعمال_sem_2_5',
      name: 'تطبيقات في القانون',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_إدارة_أعمال_sem_2_6',
      name: 'الفقه 1',
      specializationIds: ["1"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_إدارة_أعمال_sem_2_7',
      name: 'الدراسات الأدبية',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_إدارة_أعمال_sem_2_8',
      name: 'الدراسات النفسية والاجتماعية',
      specializationIds: ["6"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_إدارة_أعمال_sem_2_9',
      name: 'التقنية الرقمية 2',
      specializationIds: ["7"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_إدارة_أعمال_sem_2_10',
      name: 'المواطنة الرقمية',
      specializationIds: ["7"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_إدارة_أعمال_sem_2_11',
      name: 'المهارات الحياتية',
      specializationIds: ["17"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_إدارة_أعمال_sem_2_12',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'إدارة أعمال',
    },
  ],
  'excel_1447_high_grade_3_pathway_شرعي_sem_1': [
    {
      id: 'excel_1447_high_grade_3_pathway_شرعي_sem_1_1',
      name: 'القرآن الكريم 2',
      specializationIds: ["1"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_شرعي_sem_1_2',
      name: 'اللغة الإنجليزية 3',
      specializationIds: ["5"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_شرعي_sem_1_3',
      name: 'الفقه 2',
      specializationIds: ["1"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_شرعي_sem_1_4',
      name: 'مبادئ القانون',
      specializationIds: [],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_شرعي_sem_1_5',
      name: 'الدراسات البلاغية والنقدية',
      specializationIds: [],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_شرعي_sem_1_6',
      name: 'التفسير 2',
      specializationIds: ["1"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_شرعي_sem_1_7',
      name: 'الفرائض',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_شرعي_sem_1_8',
      name: 'مشروع التخرج',
      specializationIds: [],
      periodsPerClass: 1,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_شرعي_sem_1_9',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 1,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
  ],
  'excel_1447_high_grade_3_pathway_شرعي_sem_2': [
    {
      id: 'excel_1447_high_grade_3_pathway_شرعي_sem_2_1',
      name: 'القرآن الكريم 2',
      specializationIds: ["1"],
      periodsPerClass: 5,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_شرعي_sem_2_2',
      name: 'اللغة الإنجليزية 3',
      specializationIds: ["5"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_شرعي_sem_2_3',
      name: 'أصول الفقه',
      specializationIds: ["1"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_شرعي_sem_2_4',
      name: 'الفقه 1',
      specializationIds: ["1"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_شرعي_sem_2_5',
      name: 'الدراسات الأدبية',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_شرعي_sem_2_6',
      name: 'الدراسات النفسية والاجتماعية',
      specializationIds: ["6"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_شرعي_sem_2_7',
      name: 'التقنية الرقمية 2',
      specializationIds: ["7"],
      periodsPerClass: 4,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_شرعي_sem_2_8',
      name: 'تطبيقات في القانون',
      specializationIds: [],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_شرعي_sem_2_9',
      name: 'المواطنة الرقمية',
      specializationIds: ["7"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_شرعي_sem_2_10',
      name: 'المهارات الحياتية',
      specializationIds: ["17"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_شرعي_sem_2_11',
      name: 'البحث ومصادر المعلومات',
      specializationIds: ["4"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_شرعي_sem_2_12',
      name: 'التربية الصحية والبدنية 2',
      specializationIds: ["9"],
      periodsPerClass: 2,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
    {
      id: 'excel_1447_high_grade_3_pathway_شرعي_sem_2_13',
      name: 'النشاط',
      specializationIds: [],
      periodsPerClass: 3,
      phases: [Phase.HIGH],
      department: 'شرعي',
    },
  ],
};
