import { Phase, Subject } from './types';


// ===== الابتدائية (تحفيظ) =====

export const template_الابتدائية_تحفيظ_الصف_الأول: Subject[] = [
  {
    id: "الا_الص_1",
    name: "اللغة العربية",
    specializationIds: [],
    periodsPerClass: 8,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "الا_الص_2",
    name: "الرياضيات",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
];

export const template_الابتدائية_تحفيظ_الصف_الأول_الثاني: Subject[] = [
  {
    id: "الا_الص_1",
    name: "العلوم",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
];

export const template_الابتدائية_تحفيظ_الصف_الأول_الثاني_الثالث: Subject[] = [
  {
    id: "الا_الص_1",
    name: "القرآن الكريم والدراسات الإسلامية",
    specializationIds: [],
    periodsPerClass: 9,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "الا_الص_2",
    name: "اللغة الإنجليزية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "الا_الص_3",
    name: "التربية الفنية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "الا_الص_4",
    name: "التربية البدنية والدفاع عن النفس",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "الا_الص_5",
    name: "المهارات الحياتية والأسرية",
    specializationIds: [],
    periodsPerClass: 6,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "الا_الص_6",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
];

export const template_الابتدائية_تحفيظ_الصف_الثالث: Subject[] = [
  {
    id: "الا_الص_1",
    name: "اللغة العربية",
    specializationIds: [],
    periodsPerClass: 6,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "الا_الص_2",
    name: "العلوم",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
];

export const template_الابتدائية_تحفيظ_الصف_الثاني: Subject[] = [
  {
    id: "الا_الص_1",
    name: "اللغة العربية",
    specializationIds: [],
    periodsPerClass: 7,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
];

export const template_الابتدائية_تحفيظ_الصف_الثاني_الثالث: Subject[] = [
  {
    id: "الا_الص_1",
    name: "الرياضيات",
    specializationIds: [],
    periodsPerClass: 6,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
];

export const template_الابتدائية_تحفيظ_الصفوف_العليا_4-6: Subject[] = [
  {
    id: "الا_الص_1",
    name: "القرآن الكريم والدراسات الإسلامية",
    specializationIds: [],
    periodsPerClass: 8,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "الا_الص_2",
    name: "التجويد",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "الا_الص_3",
    name: "اللغة العربية",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "الا_الص_4",
    name: "الدراسات الاجتماعية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "الا_الص_5",
    name: "الرياضيات",
    specializationIds: [],
    periodsPerClass: 6,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "الا_الص_6",
    name: "العلوم",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "الا_الص_7",
    name: "اللغة الإنجليزية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "الا_الص_8",
    name: "المهارات الرقمية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "الا_الص_9",
    name: "التربية الفنية",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "الا_الص_10",
    name: "التربية البدنية والدفاع عن النفس",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
  {
    id: "الا_الص_11",
    name: "المهارات الحياتية والأسرية",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.ELEMENTARY],
    department: "تحفيظ",
  },
];


// ===== الابتدائية (عام) =====

export const template_الابتدائية_عام_الصف_الأول: Subject[] = [
  {
    id: "الا_الص_1",
    name: "اللغة العربية",
    specializationIds: [],
    periodsPerClass: 8,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "الا_الص_2",
    name: "الرياضيات",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
];

export const template_الابتدائية_عام_الصف_الأول_الثاني: Subject[] = [
  {
    id: "الا_الص_1",
    name: "العلوم",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
];

export const template_الابتدائية_عام_الصف_الأول_الثاني_الثالث: Subject[] = [
  {
    id: "الا_الص_1",
    name: "القرآن الكريم والدراسات الإسلامية",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "الا_الص_2",
    name: "اللغة الإنجليزية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "الا_الص_3",
    name: "التربية الفنية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "الا_الص_4",
    name: "التربية البدنية والدفاع عن النفس",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "الا_الص_5",
    name: "المهارات الحياتية والأسرية",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "الا_الص_6",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
];

export const template_الابتدائية_عام_الصف_الثالث: Subject[] = [
  {
    id: "الا_الص_1",
    name: "اللغة العربية",
    specializationIds: [],
    periodsPerClass: 6,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "الا_الص_2",
    name: "العلوم",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
];

export const template_الابتدائية_عام_الصف_الثاني: Subject[] = [
  {
    id: "الا_الص_1",
    name: "القرآن الكريم والدراسات الإسلامية",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "الا_الص_2",
    name: "اللغة العربية",
    specializationIds: [],
    periodsPerClass: 7,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
];

export const template_الابتدائية_عام_الصف_الثاني_الثالث: Subject[] = [
  {
    id: "الا_الص_1",
    name: "الرياضيات",
    specializationIds: [],
    periodsPerClass: 6,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
];

export const template_الابتدائية_عام_الصفوف_العليا_4-6: Subject[] = [
  {
    id: "الا_الص_1",
    name: "القرآن الكريم والدراسات الإسلامية",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "الا_الص_2",
    name: "اللغة العربية",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "الا_الص_3",
    name: "الدراسات الاجتماعية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "الا_الص_4",
    name: "الرياضيات",
    specializationIds: [],
    periodsPerClass: 6,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "الا_الص_5",
    name: "العلوم",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "الا_الص_6",
    name: "اللغة الإنجليزية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "الا_الص_7",
    name: "المهارات الرقمية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "الا_الص_8",
    name: "التربية الفنية",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "الا_الص_9",
    name: "التربية البدنية والدفاع عن النفس",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "الا_الص_10",
    name: "المهارات الحياتية والأسرية",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
  {
    id: "الا_الص_11",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.ELEMENTARY],
    department: "عام",
  },
];


// ===== السنة الأولى الثانوية المشتركة =====

export const template_السنة_الأولى_الثانوية_المشتركة_الأول: Subject[] = [
  {
    id: "الس_الأ_1",
    name: "القرآن الكريم وتفسيره",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_2",
    name: "الرياضيات 1",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_3",
    name: "اللغة الإنجليزية 1",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_4",
    name: "التقنية الرقمية 1",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_5",
    name: "الكفايات اللغوية 1",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_6",
    name: "مادة العلوم (كيمياء/فيزياء)",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_7",
    name: "التفكير الناقد",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_8",
    name: "التربية الصحية والبدنية 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
];

export const template_السنة_الأولى_الثانوية_المشتركة_الثاني: Subject[] = [
  {
    id: "الس_الث_1",
    name: "الرياضيات 1",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_2",
    name: "اللغة الإنجليزية 1",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_3",
    name: "التقنية الرقمية 1",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_4",
    name: "الأحياء 1",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_5",
    name: "مادة العلوم (كيمياء/فيزياء)",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_6",
    name: "الكفايات اللغوية 1",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_7",
    name: "علم البيئة",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_8",
    name: "الحديث 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_9",
    name: "المعرفة المالية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_10",
    name: "الدراسات الاجتماعية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_11",
    name: "التربية المهنية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_12",
    name: "التربية الصحية والبدنية 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
];


// ===== السنة الثالثة الثانوية مسار إدارة أعمال =====

export const template_السنة_الثالثة_الثانوية_مسار_إدارة_أعمال_الأول: Subject[] = [
  {
    id: "الس_الأ_1",
    name: "اللغة الإنجليزية 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_2",
    name: "إدارة الفعاليات",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_3",
    name: "تخطيط الحملات التسويقية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_4",
    name: "مبادئ القانون",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_5",
    name: "الدراسات البلاغية والنقدية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_6",
    name: "الإحصاء",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_7",
    name: "التربية الصحية والبدنية 2",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_8",
    name: "البحث ومصادر المعلومات",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_9",
    name: "مشروع التخرج",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_10",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.HIGH],
    department: "عام",
  },
];

export const template_السنة_الثالثة_الثانوية_مسار_إدارة_أعمال_الثاني: Subject[] = [
  {
    id: "الس_الث_1",
    name: "اللغة الإنجليزية 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_2",
    name: "إدارة الفعاليات",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_3",
    name: "تخطيط الحملات التسويقية",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_4",
    name: "السكرتارية والإدارة المكتبية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_5",
    name: "تطبيقات في القانون",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_6",
    name: "الفقه 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_7",
    name: "الدراسات الأدبية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_8",
    name: "الدراسات النفسية والاجتماعية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_9",
    name: "التقنية الرقمية 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_10",
    name: "المواطنة الرقمية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_11",
    name: "المهارات الحياتية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_12",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
];


// ===== السنة الثالثة الثانوية مسار حاسب وهندسة =====

export const template_السنة_الثالثة_الثانوية_مسار_حاسب_وهندسة_الأول: Subject[] = [
  {
    id: "الس_الأ_1",
    name: "الرياضيات 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_2",
    name: "اللغة الإنجليزية 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_3",
    name: "الفيزياء 3",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_4",
    name: "الكيمياء 3",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_5",
    name: "علوم الأرض والفضاء",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_6",
    name: "الذكاء الاصطناعي",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_7",
    name: "هندسة البرمجيات",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_8",
    name: "التربية الصحية والبدنية 2",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_9",
    name: "مشروع التخرج",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_10",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.HIGH],
    department: "عام",
  },
];

export const template_السنة_الثالثة_الثانوية_مسار_حاسب_وهندسة_الثاني: Subject[] = [
  {
    id: "الس_الث_1",
    name: "الرياضيات 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_2",
    name: "اللغة الإنجليزية 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_3",
    name: "الأمن السيبراني",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_4",
    name: "التصميم الهندسي",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_5",
    name: "الفقه 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_6",
    name: "المهارات الحياتية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_7",
    name: "البحث ومصادر المعلومات",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_8",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
];


// ===== السنة الثالثة الثانوية مسار شرعي =====

export const template_السنة_الثالثة_الثانوية_مسار_شرعي_الأول: Subject[] = [
  {
    id: "الس_الأ_1",
    name: "القرآن الكريم 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_2",
    name: "اللغة الإنجليزية 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_3",
    name: "الفقه 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_4",
    name: "مبادئ القانون",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_5",
    name: "الدراسات البلاغية والنقدية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_6",
    name: "التفسير 2",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_7",
    name: "الفرائض",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_8",
    name: "مشروع التخرج",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_9",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.HIGH],
    department: "عام",
  },
];

export const template_السنة_الثالثة_الثانوية_مسار_شرعي_الثاني: Subject[] = [
  {
    id: "الس_الث_1",
    name: "القرآن الكريم 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_2",
    name: "اللغة الإنجليزية 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_3",
    name: "أصول الفقه",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_4",
    name: "الفقه 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_5",
    name: "الدراسات الأدبية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_6",
    name: "الدراسات النفسية والاجتماعية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_7",
    name: "التقنية الرقمية 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_8",
    name: "تطبيقات في القانون",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_9",
    name: "المواطنة الرقمية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_10",
    name: "المهارات الحياتية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_11",
    name: "البحث ومصادر المعلومات",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_12",
    name: "التربية الصحية والبدنية 2",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_13",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
];


// ===== السنة الثالثة الثانوية مسار صحة وحياة =====

export const template_السنة_الثالثة_الثانوية_مسار_صحة_وحياة_الأول: Subject[] = [
  {
    id: "الس_الأ_1",
    name: "الرياضيات 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_2",
    name: "اللغة الإنجليزية 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_3",
    name: "الأحياء 3",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_4",
    name: "أنظمة جسم الإنسان",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_5",
    name: "علوم الأرض والفضاء",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_6",
    name: "المهارات الحياتية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_7",
    name: "التربية الصحية والبدنية 2",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_8",
    name: "مشروع التخرج",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_9",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
];

export const template_السنة_الثالثة_الثانوية_مسار_صحة_وحياة_الثاني: Subject[] = [
  {
    id: "الس_الث_1",
    name: "الرياضيات 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_2",
    name: "اللغة الإنجليزية 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_3",
    name: "الفيزياء 3",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_4",
    name: "الكيمياء 3",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_5",
    name: "الفقه 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_6",
    name: "الإحصاء",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_7",
    name: "البحث ومصادر المعلومات",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_8",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.HIGH],
    department: "عام",
  },
];


// ===== السنة الثالثة الثانوية مسار عام =====

export const template_السنة_الثالثة_الثانوية_مسار_عام_الأول: Subject[] = [
  {
    id: "الس_الأ_1",
    name: "الرياضيات 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_2",
    name: "اللغة الإنجليزية 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_3",
    name: "الفيزياء 3",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_4",
    name: "الكيمياء 3",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_5",
    name: "الأحياء 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_6",
    name: "علوم الأرض والفضاء",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_7",
    name: "المجال الاختياري",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_8",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.HIGH],
    department: "عام",
  },
];

export const template_السنة_الثالثة_الثانوية_مسار_عام_الثاني: Subject[] = [
  {
    id: "الس_الث_1",
    name: "الرياضيات 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_2",
    name: "اللغة الإنجليزية 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_3",
    name: "الفيزياء 3",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_4",
    name: "الكيمياء 3",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_5",
    name: "الأحياء 3",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_6",
    name: "علوم الأرض والفضاء",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_7",
    name: "الفقه 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_8",
    name: "الدراسات الأدبية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_9",
    name: "الدراسات النفسية والاجتماعية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_10",
    name: "التقنية الرقمية 3",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_11",
    name: "المواطنة الرقمية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_12",
    name: "المجال الاختياري",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_13",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
];


// ===== السنة الثانية الثانوية إدارة أعمال =====

export const template_السنة_الثانية_الثانوية_إدارة_أعمال_الأول: Subject[] = [
  {
    id: "الس_الأ_1",
    name: "اللغة الإنجليزية 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_2",
    name: "صناعة القرار في الأعمال",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_3",
    name: "مقدمة في الأعمال",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_4",
    name: "الكفايات اللغوية 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_5",
    name: "الإدارة المالية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_6",
    name: "التوحيد 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_7",
    name: "التاريخ",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_8",
    name: "اللياقة والثقافة الصحية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_9",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
];

export const template_السنة_الثانية_الثانوية_إدارة_أعمال_الثاني: Subject[] = [
  {
    id: "الس_الث_1",
    name: "اللغة الإنجليزية 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_2",
    name: "صناعة القرار في الأعمال",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_3",
    name: "مقدمة في الأعمال",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_4",
    name: "مبادئ الاقتصاد",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_5",
    name: "مبادئ الإدارة",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_6",
    name: "التفسير 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_7",
    name: "الجغرافيا",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_8",
    name: "الفنون",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_9",
    name: "اللياقة والثقافة الصحية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_10",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
];


// ===== السنة الثانية الثانوية صحة وحياة =====

export const template_السنة_الثانية_الثانوية_صحة_وحياة_الأول: Subject[] = [
  {
    id: "الس_الأ_1",
    name: "الرياضيات 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_2",
    name: "اللغة الإنجليزية 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_3",
    name: "الكيمياء 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_4",
    name: "الأحياء 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_5",
    name: "مبادئ العلوم الصحية",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_6",
    name: "الكفايات اللغوية 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_7",
    name: "اللياقة والثقافة الصحية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_8",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
];

export const template_السنة_الثانية_الثانوية_صحة_وحياة_الثاني: Subject[] = [
  {
    id: "الس_الث_1",
    name: "الرياضيات 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_2",
    name: "اللغة الإنجليزية 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_3",
    name: "الفيزياء 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_4",
    name: "الرعاية الصحية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_5",
    name: "التقنية الرقمية 2",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_6",
    name: "التوحيد 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_7",
    name: "اللياقة والثقافة الصحية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_8",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
];


// ===== السنة الثانية الثانوية مسار حاسب وهندسة =====

export const template_السنة_الثانية_الثانوية_مسار_حاسب_وهندسة_الأول: Subject[] = [
  {
    id: "الس_الأ_1",
    name: "الرياضيات 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_2",
    name: "اللغة الإنجليزية 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_3",
    name: "الفيزياء 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_4",
    name: "إنترنت الأشياء 1-1",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_5",
    name: "الكفايات اللغوية 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_6",
    name: "التاريخ",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_7",
    name: "اللياقة والثقافة الصحية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_8",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
];

export const template_السنة_الثانية_الثانوية_مسار_حاسب_وهندسة_الثاني: Subject[] = [
  {
    id: "الس_الث_1",
    name: "الرياضيات 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_2",
    name: "اللغة الإنجليزية 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_3",
    name: "الكيمياء 2",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_4",
    name: "علم البيانات",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_5",
    name: "الهندسة",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_6",
    name: "التوحيد 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_7",
    name: "الجغرافيا",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_8",
    name: "اللياقة والثقافة الصحية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_9",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
];


// ===== السنة الثانية الثانوية مسار شرعي =====

export const template_السنة_الثانية_الثانوية_مسار_شرعي_الأول: Subject[] = [
  {
    id: "الس_الأ_1",
    name: "القرآن الكريم 1",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_2",
    name: "اللغة الإنجليزية 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_3",
    name: "الكفايات اللغوية 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_4",
    name: "القراءات 1",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_5",
    name: "الحديث 2",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_6",
    name: "التوحيد 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_7",
    name: "التاريخ",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_8",
    name: "اللياقة والثقافة الصحية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_9",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
];

export const template_السنة_الثانية_الثانوية_مسار_شرعي_الثاني: Subject[] = [
  {
    id: "الس_الث_1",
    name: "القرآن الكريم 1",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_2",
    name: "اللغة الإنجليزية 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_3",
    name: "علوم القرآن",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_4",
    name: "القراءات 2",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_5",
    name: "مصطلح الحديث",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_6",
    name: "التوحيد 2",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_7",
    name: "الجغرافيا",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_8",
    name: "الفنون",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_9",
    name: "اللياقة والثقافة الصحية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_10",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
];


// ===== السنة الثانية الثانوية مسار عام =====

export const template_السنة_الثانية_الثانوية_مسار_عام_الأول: Subject[] = [
  {
    id: "الس_الأ_1",
    name: "الرياضيات 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_2",
    name: "اللغة الإنجليزية 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_3",
    name: "الفيزياء 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_4",
    name: "الكيمياء 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_5",
    name: "الأحياء 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_6",
    name: "الكفايات اللغوية 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_7",
    name: "التاريخ",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_8",
    name: "اللياقة والثقافة الصحية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الأ_9",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
];

export const template_السنة_الثانية_الثانوية_مسار_عام_الثاني: Subject[] = [
  {
    id: "الس_الث_1",
    name: "الرياضيات 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_2",
    name: "اللغة الإنجليزية 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_3",
    name: "الكيمياء 2",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_4",
    name: "الأحياء 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_5",
    name: "التقنية الرقمية 2",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_6",
    name: "التوحيد 1",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_7",
    name: "الجغرافيا",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_8",
    name: "الفنون",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_9",
    name: "اللياقة والثقافة الصحية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الس_الث_10",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.HIGH],
    department: "عام",
  },
];


// ===== الصف الدراسي =====

export const template_الصف_الدراسي_الفصل: Subject[] = [
  {
    id: "الص_الف_1",
    name: "المادة الدراسية",
    specializationIds: [],
    periodsPerClass: 0,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الص_الف_2",
    name: "المادة الدراسية",
    specializationIds: [],
    periodsPerClass: 0,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الص_الف_3",
    name: "المادة الدراسية",
    specializationIds: [],
    periodsPerClass: 0,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الص_الف_4",
    name: "المادة الدراسية",
    specializationIds: [],
    periodsPerClass: 0,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الص_الف_5",
    name: "المادة الدراسية",
    specializationIds: [],
    periodsPerClass: 0,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الص_الف_6",
    name: "المادة الدراسية",
    specializationIds: [],
    periodsPerClass: 0,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الص_الف_7",
    name: "المادة الدراسية",
    specializationIds: [],
    periodsPerClass: 0,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الص_الف_8",
    name: "المادة الدراسية",
    specializationIds: [],
    periodsPerClass: 0,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الص_الف_9",
    name: "المادة الدراسية",
    specializationIds: [],
    periodsPerClass: 0,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الص_الف_10",
    name: "المادة الدراسية",
    specializationIds: [],
    periodsPerClass: 0,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الص_الف_11",
    name: "المادة الدراسية",
    specializationIds: [],
    periodsPerClass: 0,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الص_الف_12",
    name: "المادة الدراسية",
    specializationIds: [],
    periodsPerClass: 0,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الص_الف_13",
    name: "المادة الدراسية",
    specializationIds: [],
    periodsPerClass: 0,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الص_الف_14",
    name: "المادة الدراسية",
    specializationIds: [],
    periodsPerClass: 0,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الص_الف_15",
    name: "المادة الدراسية",
    specializationIds: [],
    periodsPerClass: 0,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الص_الف_16",
    name: "المادة الدراسية",
    specializationIds: [],
    periodsPerClass: 0,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الص_الف_17",
    name: "المادة الدراسية",
    specializationIds: [],
    periodsPerClass: 0,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الص_الف_18",
    name: "المادة الدراسية",
    specializationIds: [],
    periodsPerClass: 0,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الص_الف_19",
    name: "المادة الدراسية",
    specializationIds: [],
    periodsPerClass: 0,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الص_الف_20",
    name: "المادة الدراسية",
    specializationIds: [],
    periodsPerClass: 0,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الص_الف_21",
    name: "المادة الدراسية",
    specializationIds: [],
    periodsPerClass: 0,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الص_الف_22",
    name: "المادة الدراسية",
    specializationIds: [],
    periodsPerClass: 0,
    phases: [Phase.HIGH],
    department: "عام",
  },
];


// ===== المتوسطة (تحفيظ) =====

export const template_المتوسطة_تحفيظ_الصف_الأول_والثاني: Subject[] = [
  {
    id: "الم_الص_1",
    name: "القرآن الكريم والدراسات الإسلامية",
    specializationIds: [],
    periodsPerClass: 8,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
  {
    id: "الم_الص_2",
    name: "اللغة العربية",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
];

export const template_المتوسطة_تحفيظ_الصف_الأول_والثاني_والثالث: Subject[] = [
  {
    id: "الم_الص_1",
    name: "التجويد",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
  {
    id: "الم_الص_2",
    name: "الدراسات الاجتماعية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
  {
    id: "الم_الص_3",
    name: "الرياضيات",
    specializationIds: [],
    periodsPerClass: 6,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
  {
    id: "الم_الص_4",
    name: "العلوم",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
  {
    id: "الم_الص_5",
    name: "اللغة الإنجليزية",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
  {
    id: "الم_الص_6",
    name: "المهارات الرقمية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
  {
    id: "الم_الص_7",
    name: "التربية الفنية",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
  {
    id: "الم_الص_8",
    name: "التربية البدنية والدفاع عن النفس",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
  {
    id: "الم_الص_9",
    name: "المهارات الحياتية والأسرية",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
];

export const template_المتوسطة_تحفيظ_الصف_الثالث: Subject[] = [
  {
    id: "الم_الص_1",
    name: "القرآن الكريم والدراسات الإسلامية",
    specializationIds: [],
    periodsPerClass: 7,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
  {
    id: "الم_الص_2",
    name: "التفكير الناقد",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
  {
    id: "الم_الص_3",
    name: "اللغة العربية",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.MIDDLE],
    department: "تحفيظ",
  },
];


// ===== المتوسطة (عام) =====

export const template_المتوسطة_عام_الصف_الأول_والثاني: Subject[] = [
  {
    id: "الم_الص_1",
    name: "اللغة العربية",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
  {
    id: "الم_الص_2",
    name: "الدراسات الاجتماعية",
    specializationIds: [],
    periodsPerClass: 3,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
];

export const template_المتوسطة_عام_الصف_الأول_والثاني_والثالث: Subject[] = [
  {
    id: "الم_الص_1",
    name: "القرآن الكريم والدراسات الإسلامية",
    specializationIds: [],
    periodsPerClass: 5,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
  {
    id: "الم_الص_2",
    name: "الرياضيات",
    specializationIds: [],
    periodsPerClass: 6,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
  {
    id: "الم_الص_3",
    name: "العلوم",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
  {
    id: "الم_الص_4",
    name: "اللغة الإنجليزية",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
  {
    id: "الم_الص_5",
    name: "المهارات الرقمية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
  {
    id: "الم_الص_6",
    name: "التربية الفنية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
  {
    id: "الم_الص_7",
    name: "التربية البدنية والدفاع عن النفس",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
  {
    id: "الم_الص_8",
    name: "المهارات الحياتية والأسرية",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
  {
    id: "الم_الص_9",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
];

export const template_المتوسطة_عام_الصف_الثالث: Subject[] = [
  {
    id: "الم_الص_1",
    name: "اللغة العربية",
    specializationIds: [],
    periodsPerClass: 4,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
  {
    id: "الم_الص_2",
    name: "الدراسات الاجتماعية",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
  {
    id: "الم_الص_3",
    name: "التفكير الناقد",
    specializationIds: [],
    periodsPerClass: 2,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
  {
    id: "الم_الص_4",
    name: "النشاط",
    specializationIds: [],
    periodsPerClass: 1,
    phases: [Phase.MIDDLE],
    department: "عام",
  },
];


// ===== المرحلة =====

export const template_المرحلة_الصف_الدراسي: Subject[] = [
  {
    id: "الم_الص_1",
    name: "المادة الدراسية",
    specializationIds: [],
    periodsPerClass: 0,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الم_الص_2",
    name: "المادة الدراسية",
    specializationIds: [],
    periodsPerClass: 0,
    phases: [Phase.HIGH],
    department: "عام",
  },
  {
    id: "الم_الص_3",
    name: "المادة الدراسية",
    specializationIds: [],
    periodsPerClass: 0,
    phases: [Phase.HIGH],
    department: "عام",
  },
];
